import { Injectable } from '@angular/core';

import { SQLite, SQLiteObject } from '@ionic-native/sqlite';
import { LoadingController, Loading } from 'ionic-angular';

/*
  Generated class for the DatabaseProvider provider.

  See https://angular.io/guide/dependency-injection for more info on providers
  and Angular DI.
*/
@Injectable()
export class DatabaseProvider {

  loader: Loading;

  constructor(public sqlite: SQLite, public loadingCtrl: LoadingController) {
    console.log('Hello DatabaseProvider Provider');
  }

  presentLoading() {
    this.loader = this.loadingCtrl.create({
      content: "Cargando..."
    });
    this.loader.present();
  }

  private myDb: any;

  public init(){
    this.openDatabase();
  }

  private openDatabase(){
    this.sqlite.create({
      name: 'arboles.db',
      location: 'default'
    })
    .then((db) => {
      console.log(db);
      this.myDb = db;
      this.execute(db);
    })
    .catch( error => {
      console.error(error);
    });
  }

  public getAll(){
    this.presentLoading();
    let sql = 'SELECT * FROM arboles';
    return this.myDb.executeSql(sql, [])
    .then(response => {
      let arboles = [];
      for (let index = 0; index < response.rows.length; index++) {
        arboles.push( response.rows.item(index) );
      }
      this.loader.dismiss();
      return Promise.resolve( arboles );
    })
    .catch(error => Promise.reject(error));
  }

  public query(cond: string){
    this.presentLoading();
    let sql = 'SELECT * FROM arboles where ' + cond;
    return this.myDb.executeSql(sql, [])
    .then(response => {
      let arboles = [];
      for (let index = 0; index < response.rows.length; index++) {
        arboles.push( response.rows.item(index) );
      }
      this.loader.dismiss();
      return Promise.resolve( arboles );
    })
    .catch(error => Promise.reject(error));
  }

  private execute(db: SQLiteObject){
    db.executeSql(this.createTable,[])
    .then(response => {
      db.executeSql(this.insertData,[])
      .then(response => {
        console.log('database instanciated');
      })
      .catch(error => console.error(error));
    })
    .catch(error => console.error(error));
  }

  private createTable: string = `CREATE TABLE IF NOT EXISTS arboles (
    _id	INTEGER NOT NULL,
    especie	TEXT,
    autor	TEXT,
    nombre1	TEXT,
    nombre2	TEXT,
    nombre3	TEXT,
    nombre4	TEXT,
    nombre5	TEXT,
    nombre6	TEXT,
    nombre7	TEXT,
    formadevida	TEXT,
    presenciaespinas	TEXT,
    disposicionhoja	TEXT,
    tipohoja	TEXT,
    formahoja	TEXT,
    bordehoja	TEXT,
    colorflor	TEXT,
    tipofruto	TEXT,
    familia	TEXT,
    caracteristicas	TEXT,
    habitat	TEXT,
    estatus	TEXT,
    observaciones	TEXT,
    PRIMARY KEY(_id)
  );`;

  private insertData: string = `INSERT INTO arboles VALUES (1,'Acacia bonariensis','Gillies ex Hook. & Arn.','Acacia','garabato','uña de gato','ñapindá','','','','Arbusto','Si','Alterna','Compuesta','Bipinnada','Entero','Amarillo a anaranjado','Seco','Fabaceae','Arbusto erecto o apoyante con aguijones recurvos, dispersos. Hojas compuestas, bipinnadas con 6-11 pares de pinnas y numerosos foliolos. Flores amarillas pálidas, en cabezuelas, dispuestas en panojas terminales. Fruto legumbre alargada. Semilla elíptica dura, castaño-olivácea. Florece y fructifica de diciembre a marzo.','Bosque en galería, zona bajas y bosque xerófilo.','Endémica','Ornamental, para formar cercos vivos. Melífera. Medicinal (uso depurativo y antisifilítico del tallo y la raíz).'),
  (2,'Acacia caven','(Molina) Molina.','Acacia','espinillo','aromito','','','','','Árbol','Si','Alterna','Compuesta','Bipinnada','Entero','Amarillo a anaranjado','Seco','Fabaceae','Árbol de 2-5 m de altura, de copa ancha con espinas largas, blanquecinas, rectas y geminadas. Hojas pequeñas, bipinnadas con 3-10 pares de pinnas y numerosos folíolos; fasciculadas. Flores amarillo-doradas, dispuestas en cabezuelas globosas fasciculadas. El fruto es una legumbre gruesa, cilíndrico-fusiforme a ovoide--subglobosa, negra, indehiscente, flotante, de dispersión hidrocora. Semillas verdosas. Florece entre agosto y septiembre.','Bosques semixerófilos y ribereños.','Nativa','Ornamental. Melífera. Se utiliza la madera para hacer leña, fabricar postes, mango de herramientas, instrumentos musicales y para fabricar carbón. El aceite esencial tiene un amplio uso en perfumería. Medicinal (el polvo de las hojas se utiliza como vulnerario, las semillas en infusión tienen propiedades digestivas y estornutatorias, la raíz en decocción es purgante, emética y diurética).'),
  (3,'Acanthostyles buniifolius','(Hook. & Arn.) R.M. King & H. Rob.','Acanthostyles','chilca','mío mío','romerillo','','','','Arbusto','No','Opuesta','Simple','Otra','Entero','Azúl a púrpura','Seco','Asteraceae','Arbusto, de 0,8 -2 m. de altura, densamente ramoso. Hojas opuestas, simples y lineales o bien pinnatisectas, glabras o ligeramente puberulentas, enteras, de 30 - 60 mm. de long. x 1,3 mm. de lat. Flores violáceas en capítulos pequeños, muy numerosos, agrupados en amplias panojas más o menos péndulas. Fruto aquenio algo piloso en las aristas. Papús blanco. Florece y fructifica en verano.','En campos, palmares, praderas, estepas y bosques xerófilos.','Nativa','Ornamental. Medicinal (Tallos y hojas usados para la debilidad nerviosa y del cerebro. Bueno para el estómago como digestivo: alivia el hígado y los riñones. En infusión en dolencias agudas).'),
  (4,'Allophylus edulis','(A. St.-Hil., A. Juss. & Cambess.) Hieron. ex Niederl.','Allophylus','chal chal','coloradillo','koku','','','','Árbol','No','Alterna','Compuesta','Trifoliada','Dentado','Blanco a verdoso','Carnoso','Sapindaceae','Árbol de hasta 15 m de altura, corteza escamosa. Hojas compuestas, trifoliadas, cartáceas, dentado-aserradas con peciolo semiterete y canaliculado. Flores pequeñas, amarillo-crema, dispuestas en inflorescencias espiciformes. Fruto esquizocarpico, con 1-3 mericarpios drupáceos, carnosos de color rojo brillante. Florece en primavera y fructifica en verano.','Bosques ribereños, palmares.','Nativa','Ornamental. Melífera. Frutos comestibles. Madera utilizada para leña y en carpintería. Medicinal (hojas en infusión utilizada como digestiva y refrescante).'),
  (5,'Aloysia gratissima','(Gillies & Hook. ex Hook.) Tronc. var. gratissima','Aloysia','romerillo','azahar del campo','niño-urupá','cedrón del monte','','','Arbusto','Si','Opuesta','Simple','Elíptica','Entero','Blanco a verdoso','Seco','Verbenaceae','Arbusto aromático de hasta 3 metros de altura, ramoso, con ramas agudo espinosas. Hojas simples, enteras o paucidentada, elípticas oblongo-lanceoladas de 3,5 cm de long. X 0,8 cm de lat., opuestas o en fascículos sobre braquiblastos laterales, generalmente discoloras, con nervio medio prominente en el envés. Flores pequeñas, blancas, fragantes, dispuestas en racimos axilares solitarios o en panojas terminales. Frutos mericarpios cilíndricos, lisos. Florece en primavera y verano.','Bosque ribereño, barrancas altas y quebradas.','Nativa','Melífera. Medicinal (ramas y hojas se usan en infusión como digestivo, anticatarral y sedante). Rica en aceites esenciales. Ornamental. Tóxica para el ganado equino.'),
  (6,'Aspidosperma quebracho - blanco','Schltdl.','Aspidosperma','quebracho blanco','','','','','','Árbol','No','Verticilada','Simple','Elíptica','Entero','Amarillo a anaranjado','Seco','Apocynaceae','Árbol de 10-20 m de altura, con corteza suberosa gruesa y rugosa. Hojas simples, elíptico-lanceolado, glabras, persistentes, coriáceas con ápice espinoso, cortamente pecioladas, dispuestas en verticilos trímeros. Inflorescencias en breves dicasios o tricasios axilares y terminales. Flor hermafrodita, actinomorfa, amarillenta. Fruto, cápsula dehiscente, verde-grisáceo-claro, bivalva, asimétrica, comprimida lateralmente. Semillas con ala membranosa.','Crece en bosques xerófilos y blanquizales.','Nativa','Árbol de gran importancia forestal. Medicinal (empleado como  antifebrífugo, antiasmático, depurativo y para el hígado). Fuente de alcaloides, entre ellos la quebraquina y aspidospermina. Muy explotada por el carbón de excelente calidad y utilizada en carpintería.'),
  (7,'Baccharis dracunculifolia','DC.','Baccharis','chilca mata ojo','','','','','','Arbusto','No','Alterna','Simple','Elíptica','Dentado','Blanco a verdoso','Seco','Asteraceae','Arbusto de 1,5-5 m de altura, dioico, densamente ramoso y hojoso. Pubescente en las ramas jóvenes y glabros en las adultas. Hojas simples, sésiles, alternas, oblongo-lanceoladas con ápice agudo, glabras o punteado- glandulosas de 20 a 40 mm de long., con margen entero o con 4 dientes. Flores, blancas, dispuestas en capítulos numerosos, cortamente pedunculados, solitarios, en las axilas de las hojas superiores. Fruto aquenio cilíndrico, costado, glabro. Florece en primavera-verano y fructifica hasta otoño.','Bosques xerófilos, matorrales, palmares y pastizales.','Nativa','Melífera. Aceite esencial con propiedad antioxidante, antimicrobiana y antiinflamatoria.'),
  (8,'Bauhinia forficata','Link ssp. pruinosa (Vogel) Fortunato & Wunderlin','Bauhinia','pata de vaca','pata de buey','pezuña de vaca','falsa caoba','','','Árbol','Si','Alterna','Simple','Otra','Entero','Blanco a verdoso','Seco','Fabaceae','Árbol de 8 a 10 m de altura, con ramas flexuosas, follaje denso, con estipulas espinescentes caducas y aguijones rectos. Hojas simples, alternas, bilobadas de 4 a 15 cm de long., con peciolo acanalado de 1-3 cm, y pulvínulos en ápice y base. Flores blancas, grandes, de 8 a 13 cm. de diám. dispuestas de forma solitaria o en racimos axilares. Fruto legumbre aplanada, castaña, dehiscente de 10 a 20 cm. de long. Semillas ovales, planas de color negro. Florece en verano y fructifica en otoño.','Bosques ribereños.','Nativa','Ornamental. Medicinal (la infusión de las hojas es utilizada como antidiabética, antinefrítica, diurética, antitusiva, cardiotónica, anticaspa; la infusión de las flores es digestiva, astringente y antihemorroidal).'),
  (9,'Berberis laurina','Thunb','Berberis','espina amarilla','','','','','','Arbusto','Si','Alterna','Simple','Ovalada','Entero','Amarillo a anaranjado','Carnoso','Berberidaceae','Arbusto espinoso, de hasta 3 m de altura, copa globosa, tallos múltiples con tres espinas amarillas, perpendiculares de 0,7 a 3,5 cm de largo y leño amarillo, dispuestas en la base del fascículo. Hojas simples, alternas en macroblastos, fasciculadas en braquiblastos dispuestas en tallos glabros, discoloras, coriáceas, láminas obovado oblongas a oblanceoladas de 7 a 10 x 1,5 a 3 cm, con nervadura principal marcada, haz lustroso y envés opaco, ápice mucronado, margen entero o dentado, base cuneada, pecíolos cortos. Flores amarillas, reunidas en inflorescencias péndulas, más largas que las hojas. Fruto baya globosa, de color negro al madurar, de 5 a 7 mm de largo y 3 a 5 de diám. Florece en primavera y fructifica en primavera-verano.','Arbusto heliófilo y semixerófilos en bordes de bosques ribereños.','Nativa','Ornamental por su floración y fructificación muy vistosa. Medicinal (astringente, febrífuga, tallos utilizados para tratamiento de quemaduras). Melífera. La raíz y corteza se utilizan para teñir lana de amarillo.'),
  (10,'Blepharocalyx salicifolius','(Kunth) O. Berg','Blepharocalyx','anacahuita','mirta','arrayán','','','','Árbol','No','Opuesta','Simple','Elíptica','Entero','Blanco a verdoso','Carnoso','Myrtaceae','Árbol, de 5 - 12 m. de altura. Hojas simples, opuestas, cortamente pecioladas, lanceoladas, glabras, de 4 - 8 cm. de long. x 1 - 2,5 cm. de lat. Flores blancas muy perfumadas, dispuestas en cimas dicótomas axilares. Fruto baya globosa, roja, anaranjada o negra según la madurez. Semillas pequeñas 1-3. Florece en primavera y fructifica en verano.','Selvas marginales y bosques ribereños.','Nativa','Ornamental. Medicinal (Hojas estomacales, digestivas y en cocimiento antileucorreicas en inyecciones; mezcladas con las de Myrcianthes pungens (O. Berg). D. Legrand contra flujos o leucorrea. Hojas y corteza de acción antitusiva, expectorante, pectoral, astringente y antidiarreica, con miel o azúcar. El polvo de hojas es utilizado como vulnerario y para curar la caída del cordón umbilical). Aromática (Contiene taninos y aceites esenciales). Utilizada para leña y carbón.'),
  (11,'Broussonetia papyrifera','(L.) Vent.','Broussonetia','morera de papel','higuerilla','','','','','Árbol','No','Alterna','Simple','Ovalada','Dentado','Blanco a verdoso','Carnoso','Moraceae','Árbol de 8-15 m de altura, dioico con látex. Corteza gris clara lisa, oscureciéndose y fisurándose con los años. Hojas simples, alternas, opuestas en el ápice de las ramas, muy variables, de lámina entera, lobada o palmatisecta, de 4,5-20 cm de long. 32-17 cm de lat. ovado-cordiformes, con margen aserrado o no, haz de color verde oscuro, escabroso y envés más claro, y blanco-tomentoso. Inflorescencias femeninas en cabezuelas globosas de 1-2 cm de diám, de color violáceo, y las masculinas son blanco-amarillentas dispuestas en amentos pedunculados. Infrutescencia (sincarpo) globosa y carnosa de color anaranjado a la madurez. Florece en primavera y fructifica en verano.','Bordes de arroyos, bosques en galerías, caminos vecinales. Es originaria del este de China (Región Chino-Japonesa).','Adventicia','Ornamental y de sombra. En su país de origen la corteza interna se usa para fabricar papel. También se utiliza en la industria textil para elaborar tejidos llamados masi. Los frutos, raíces y corteza tienen aplicaciones en la medicina tradicional china. Con su madera se fabrican muebles, cajas, lápices y cerillas; con sus ramas se trenzan canastas y cestos. Especie de muy rápido crecimiento y reproducción, que puede desestabilizar los ecosistemas convirtiéndose en una especie invasiva.'),
  (12,'Buddleja stachyoides','Cham. & Schltdl.','Buddleja','peludilla','cambará','','','','','Arbusto','No','Opuesta','Simple','Elíptica','Dentado','Amarillo a anaranjado','Seco','Scrophulariaceae','Arbusto de hasta 2 m de altura, con tomento de tricomas estrellados o ramificados y tallos cuadrangulares tomentosos. Hojas simples, opuestas, sésiles, oval-lanceoladas, tomentosas en ambas caras pero más densamente en la inferior, amplexicaules, unidas en su base por un “collar” foliáceo. Flores amarillas, tomentosas; dispuestas en cimas globosas multifloras o glomérulos subsésiles, axilares y en tirsos densos apicales. Fruto cápsula ovoide, pubescente. Florece desde fines de invierno hasta principios de primavera y fructifica en verano.','Bosque en galería, barrancas con bosques semixerófilos, campos altos y bordes de caminos.','Nativa','Ornamental. Medicinal (Empleada para combatir catarros, resfríos, diarreas, disentería y hemorroides).'),
  (13,'Butia yatay','(Mart.) Becc.','Butia','palmera yatay','yatay','butia','','','','Palmera','No','Alterna','Compuesta','Paripinnada','Entero','Amarillo a anaranjado','Carnoso','Arecaceae','Palmera, de 10 - 20 m. de altura. Hojas compuestas, palmatipinnadas, formando un penacho, de hasta 2 m. de long. Flores amarillentas dispuestas en espádices densos. Fruto drupáceo, de color amarillento anaranjado a rojizo, ovoide o elipsoide. Semillas de 1-3. Florece de octubre a febrero y fructifica de enero a abril.','Bosque ribereño y campos arenosos.','Endémica','Ornamental. Fruto comestible (elaboración de dulces, licores y blend de té). Medicinal (las semillas se comen como antihelmínticas). Hojas utilizadas para la elaboración de artesanías.'),
  (14,'Byttneria urticifolia','K. Schum.','Byttneria','amorera','','','','','','Arbusto','Si','Alterna','Simple','Ovalada','Dentado','Azúl a púrpura','Seco','Malvaceae','Arbusto apoyante, de 1-4 m de alt., hispido, con aguijones recurvados, muy aguzados. Hojas simples, pubescentes, con pecíolo de 2-5 cm de long. y lamina aovada, cordada, aserrada en el margen, de 5-8 cm de long. Flores péndulas purpúreas, en cimas axilares. El fruto es una cápsula esférica de 10-12 mm de long. x 5-10 mm de diám. Semilla ovoide, tuberculada, de color pardo. Florece y fructifica en verano y otoño.','Barrancas costeras, abundante en las selvas en galería.','Endémica','Ornamental.'),
  (15,'Caesalpinia gilliesii','(Hook.) Benth.','Caesalpinia','barba de chivo','lagaña de perro','espiga de amor','mal de ojo','disciplina de monja','','Arbusto','No','Alterna','Compuesta','Bipinnada','Entero','Amarillo a anaranjado','Seco','Fabaceae','Arbusto de hasta 3 m de altura, con ramas pubescentes y glandulosas por pelos rojizos y olor desagradable. Hojas compuestas, imparibipinnadas, glabras de 6 a 28 cm de long. De coloración verde-azulada, con estípulas papiráceas y ciliadas. Flores grandes y vistosas, con pétalos amarillo y estambres largos rojos, dispuestas en racimos piramidales terminales. Fruto vaina lineal, subfalcada, comprimida y pubescente, de 5 a 10 cm de long. Semillas comprimidas de color castaño. Florece en primavera y fructifica en verano.','Barrancas y campos altos.','Nativa','Ornamental. Las flores se utilizan para teñir de color amarillo. Medicinal (flores y ramas se aplican sobre caries y en cataplasmas contra dolores articulares, la infusión de sus hojas es utilizada como purgante y la de las flores como febrífuga).'),
  (16,'Calliandra parvifolia','(Hook. f. & Arn.) Speg.','Calliandra','plumerillo rosado','plumerillo','flor de seda','flor del cielo','','','Arbusto','No','Alterna','Compuesta','Bipinnada','Entero','Rojo a rosado','Seco','Fabaceae','Arbusto inerme, ramificado tendido de hasta 3 m de altura. Hojas compuestas, vellosas, bipinnadas estipuladas, alternas, con peciolo de un centímetro y con foliolos lineales oblongos. Flores con filamentos estaminales largos, blancos en parte inferior y rosados en la parte superior, dispuestos en cabezuelas axilares grandes. Fruto legumbre comprimida, pubescente de hasta 7 cm de largo. Semillas oblongo-ovalada de 2 a 4 por fruto. Florece de noviembre a enero y fructifica de enero a abril.','Bosque ribereño, costa de ríos y arroyos.','Nativa','Ornamental. Melífera. Planta nutricia de la Mariposa Bandera Argentina (Morpho epistrophus).'),
  (17,'Calliandra tweedii','Benth.','Calliandra','plumerillo rojo','borla de obispo','socará','','','','Arbusto','No','Alterna','Compuesta','Bipinnada','Entero','Rojo a rosado','Seco','Fabaceae','Arbusto inerme de hasta 4 metros de altura, con varios tallos principales. Copa globosa y extendida. Hojas compuestas, bipinnadas dispuestas de forma alterna sobre tallo con pelos rígidos blanquecinos, foliolos pequeños, asimétricos, discolores y con un nervio principal marcado, con estipulas persistente. Flores muy vistosas, con pétalos pequeños, verdosos y estambres de hasta 5 cm de largo con filamentos rojizos, dispuestas en inflorescencias globosas capituliformes. Fruto legumbre oblonga-lanceolada, comprimida de hasta 6 cm. de largo, cubierta por pelos hispidos. Semillas elípticas, castaño-claras con manchas oscuras. Florece en primavera y fructifica en verano.','Bosque ribereño, zonas bajas y húmedas.','Nativa','Ornamental. Melífera.'),
  (18,'Castela tweedii','Planch.','Castela','granadillo','corona de cristo','','','','','Arbusto','Si','Alterna','Simple','Elíptica','Entero','Rojo a rosado','Carnoso','Simaroubaceae','Arbusto de hasta 2 metros de altura, con corteza rugosa y surcada. Hojas simples, elípticas, de base obtusa y ápice agudo, de borde entero o con 1-3 dientes, pecioladas. Espinas axilares. Flores rojizas-amarillentas, dispuestas en fascículos axilares. Fruto esquizocarpico con 1-4 mericarpos drupáceos, de color rojizo a violáceo-negro. Florece en primavera y fructifica en verano.','Bosques subxerófilos y ribereños.','Endémica','Ornamental, como cerco vivo. Medicinal (sus hojas en infusiones son utilizadas para el tratamiento de desórdenes gastrointestinales, fiebres y diarreas).'),
  (19,'Celtis ehrenbergiana','(Klotzsch) Liebm. var. ehrenbergiana','Celtis','tala','','','','','','Árbol','Si','Alterna','Simple','Ovalada','Dentado','Blanco a verdoso','Carnoso','Celtidaceae','Árbol de 3-12 m de altura, corteza grisácea y ramas en zigzag, con espinas geminadas, rectas y axilares. Hojas simples, alternas, aovadas o aovado-lanceoladas, con un pequeño mucrón apical, trinervias de borde aserrado, glabrescente o con algunos pelos, sobre todo en el envés. Flores inconspicuas, verdoso, amarillento, en glomérulos axilares. El fruto es una drupa globosa, amarillo-anaranjada; superficie del pireno irregularmente reticulada. Semilla dura y rugosa. Florece en primavera y fructifica de primavera a verano.','Montes, barrancas, orilla de arroyos y ríos.','Nativa','Forestal y ornamental, la madera dura y pesada es utilizada como leña y para hacer carbón. Los frutos son comestibles. Medicinal (es empleada como anticolérica; antidisentérica y hepática; cura catarros, dolores de pecho, cabeza, diarreas, indigestiones y el empeine). La raíz es tintórea.'),
  (20,'Celtis iguanaea','(Jacq.) Sarg.','Celtis','tala gateador','','','','','','Árbol','Si','Alterna','Simple','Elíptica','Dentado','Blanco a verdoso','Carnoso','Celtidaceae','Árbol apoyante de 3 a 12 m de altura, a veces trepador, ramas con espinas curvas y corteza lisa, color pardo claro o grisácea. Hojas simples, ovadas o elípticas de 2 a 12 cm de long. con ápice agudo y margen aserrado, hipófilo glabro a algo pubescente. Flores pequeñas, verduscas y axilares. Fruto drupa amarillo-anaranjada de 13 mm de diám. Florece en primavera y fructifica en verano y otoño.','Bosques en galería.','Nativa','Ornamental. Fruto comestible. Medicinal (hojas en infusión contra la indigestión).'),
  (21,'Cephalanthus glabratus','(Spreng.) K. Schum.','Cephalanthus','blanquillo','sarandí colorado','','','','','Arbusto','No','Verticilada','Simple','Elíptica','Entero','Blanco a verdoso','Seco','Rubiaceae','Arbusto 3-5 m de altura. Hojas simples, elípticas u ovado-elípticas con ápice agudo o acuminado, en verticilos de tres, brevemente peciolada. Estípulas triangulares. Flores blancas, dispuestas en glomérulos esféricos, largamente pedunculados. Fruto cápsula, indehiscente. Florece en primavera-verano y fructifica de verano a otoño.','Borde de ríos, arroyos, lagunas e islas, y en pajonales.','Nativa','Ornamental. Medicinal (hojas usadas como diurética, depurativa, vulnerario y astringente; la decocción de la corteza se utiliza para tratar la diabetes).'),
  (22,'Cereus uruguayanus','R. Kiesling','Cereus','cardón','cardón uruguayo','cacto candelabro','tuna candelabro','','','Cactus arborescente','Si','Verticilada','Simple','Otra','Entero','Blanco a verdoso','Carnoso','Cactaceae','Cactus arborescente de hasta 10 m de altura, muy ramificada, con ramas glaucas cuando jóvenes pasando a verde oscuras con la edad. Ramas con 6 a 9 costillas, aréolas con espinas subiguales, aciculares, de 5-10 castañas a negras de 1 a 3 cm de long. Flores blancas de 15 cm de long. Fruto baya subglobosa, anaranjada-amarillenta de 4 cm de long. Semillas negras lustrosas de 2 mm de long. Florece y fructifica en primavera y verano.','Matorrales, borde de bosques de ribera, campos altos.','Endémica','Ornamental. Fruto comestible.'),
  (23,'Citharexylum montevidense','(Spreng.) Moldenke','Citharexylum','tarumá','tarumán','espina del bañado','','','','Árbol','Si','Opuesta','Simple','Ovalada','Entero','Blanco a verdoso','Carnoso','Verbenaceae','Árbol de hasta 12 metros de altura, con corteza grisácea a castaña y ramas cuadrangulares, con 2 espinas rectas por nudo. Hojas simples, opuestas, cartáceas, con lámina obovada elíptica y discolora de 3 a 10 cm de long. Flores amarillas, perfumadas dispuestas en racimos terminales péndulos. Fruto drupa ovoide, carnosa de color rojo de 9 a 12 mm de largo. Florece de septiembre a diciembre. Fructifica de diciembre a abril.','Bosque ribereño.','Nativa','Ornamental. Madera útil en carpintería.'),
  (24,'Colletia paradoxa','(Spreng.) Escal.','Colletia','espina de la cruz','','','','','','Arbusto','Si','Opuesta','Simple','Elíptica','Entero','Blanco a verdoso','Seco','Rhamnaceae','Arbusto subáfilo, de 1 a 2,5 m de altura, con ramas espiniformes, aplanadas, triangulares decusadas, verde grisáceas. Hojas elípticas, enteras o con algunos dientes, caedizas, presentes solo en ramas jóvenes. Flores blancas, perfumadas, con forma urceolada dispuestas en las axilas. Fruto capsula tricoca de 5 mm de diám. Florece de marzo a abril y fructifica en primavera.','Arenales y campos pedregosos.','Endémica','Ornamental, utilizada como cerco vivo. Melífera. Medicinal (ramas utilizadas como tónico y febrífugo).'),
  (25,'Colletia spinosissima','J.F. Gmel.','Colletia','barba de tigre','espina cruz','quina','','','','Arbusto','Si','Opuesta','Simple','Elíptica','Entero','Blanco a verdoso','Seco','Rhamnaceae','Arbusto de hasta 4 metros de altura, con espinas y ramas espiniformes verdes. Hojas simples, elípticas u ovadas de 1 cm de long, precozmente caducas. Flores perfumadas, blancas-amarillentas, verdosas, rosadas o rojas con forma urceolada. Fruto cápsula castaña rojiza, tricoca de 5 m de diám. Florece en invierno-primavera y fructifica en primavera verano.','Barrancas ribereñas, menos común dentro del bosque de ribera.','Nativa','Melífera. Útil para formación de cercos vivos y como combustible. Utilizada antiguamente como sustituto del jabón para lavar ropa debido a su alto contenido de saponinas. Tintórea. Medicinal (uso antipirético, febrífugo, astringente y purgativo por la presencia de alcaloides amargos y triterpenos). Fertilizante natural del suelo por su simbiosis con bacterias fijadoras de nitrógeno pertenecientes al género Frankia.'),
  (26,'Croton urucurana','Baill.','Croton','sangre de drago','','','','','','Árbol','No','Alterna','Simple','Ovalada','Entero','Blanco a verdoso','Seco','Euphorbiaceae','Árbol de 3-5 m de altura, con látex rosado que al oxidarse se torna rojizo. Hojas simples, largamente pecioladas, triangular-aovadas, acuminadas, enteras o levemente denticuladas, glandulosas en la inserción del pecíolo, cubiertas en la cara inferior de un denso tomento de pelos estrellados, blanco-amarillento. Flores en racimos terminales largos, diclino monoicas. Frutos tricocos, tomentosos con tres semillas carunculadas. Florece en verano y fructifica entre marzo y abril.','Borde del ríos e islas.','Nativa','Ornamental. Utilizada en medicina popular como vermífugo, purgante, antisifilítico, hemostático y antidisentérico. El látex es empleado como cicatrizante, se aplica sobre heridas, úlceras y sobre muelas. Melífera.'),
  (27,'Croton uruguayensis','Baill.','Croton','desconocido','','','','','','Arbusto','No','Alterna','Simple','Elíptica','Entero','Blanco a verdoso','Seco','Euphorbiaceae','Arbusto, de 2 - 3 m. de altura, con pubescencia plateada. Hojas simples, lanceoladas, angostamente elípticas u oblongas, discolores, de 1 - 5,5 cm. de long. x 0,3 - 1,4 cm. de lat. Inflorescencias casi siempre unisexuales, blanco-amarillentas. Semilla subelipsoide, comprimida dorsiventralmente, castaño-oscura con carúncula subapical. Florece y fructifica en primavera.','Crece en borde de bosques en galería y palmares.','Endémica','Ornamental, follaje decorativo. Aromática.'),
  (28,'Cupania vernalis','Cambess.','Cupania','cambotá','cedrillo','ramo','ramio','','','Árbol','No','Alterna','Compuesta','Imparipinnada','Dentado','Blanco a verdoso','Carnoso','Sapindaceae','Árbol de hasta 25 m de altura, corteza gris parduzca, agrietada y ramas con pelos amarillentos. Hojas compuestas, pinnadas y alternas, de 8 a 16 foliolos discolores con raquis bicaniculado. Flores blanquecinas, pequeñas y fragantes dispuestas en cincinos. Fruto capsula de 18 mm long., coriácea con pelos amarillentos. Semillas castañas-oscuras con arilo anaranjado. Florece entre abril y mayo, y fructifica entre noviembre y diciembre.','Bosque ribereño.','Nativa','Ornamental. Melífera. Madera útil en carpintería, para producir carbón y construir hormas de zapatos. Corteza rica en taninos. Medicinal (uso digestivo, antiinflamatorio y antitusivo).'),
  (29,'Daphnosis racemosa','Griseb.','Daphnosis','envira','ibira','vira vira','','','','Arbusto','No','Alterna','Simple','Ovalada','Entero','Blanco a verdoso','Carnoso','Thymelaeaceae','Arbusto de 1 a 3 m de altura, dioico. Corteza lisa, gris clara. Hojas simples, alternas, obovadas, coriáceas, glabras, de 5-16 cm long, pecioladas. Flores unisexuales pequeñas, las masculinas blanco amarillento y las femeninas blanco verdosas dispuestas en inflorescencias axilares. Fruto baya ovoide blanco-perlada. Florece en agosto-septiembre y fructifica de noviembre a diciembre.','Bosque en galería, palmares y zonas bajas.','Nativa','Ornamental. Melífera. Uso de las fibras en la confección de cordeles rústicos y para atar.'),
  (30,'Diospyros inconstans','Jacq.','Diospyros','granadillo','maba','caqui silvestre','','','','Árbol','No','Alterna','Simple','Ovalada','Entero','Amarillo a anaranjado','Carnoso','Ebenaceae','Árbol de hasta 5 m de altura, ramoso, con lenticelas en su tronco. Hojas simples, oboval-elípticas, subcoriáceas, alternas de 3 a 11 cm de long, haz glabro y envés setuloso. Flores blanco-amarillentas, dioicas, campanuladas, trímeras o tetrámeras, subsésiles, péndulas y axilares dispuesta de 2-3 o de forma solitaria. Fruto baya globosa violáceo a negra púrpurea de 1,5 s 2,5 cm. de diám. con cáscara subcoriácea. Semillas en forma de gajo de naranja. Florece y fructifica en primavera, verano y otoño.','Bosque en galería, borde de rio y arroyos.','Nativa','Ornamental. Frutos comestibles, con los cuales se prepara licor. Madera útil para leña, carbón o en la construcción de cabos de herramientas.'),
  (31,'Discaria americana','Gillies & Hook.','Discaria','brusquilla','quina del campo','','','','','Arbusto','Si','Opuesta','Simple','Lineal','Entero','Blanco a verdoso','Seco','Rhamnaceae','Arbusto de hasta 2,5 m de altura, con tallos surcados y ramitas con espinas decusadas en los nudos, subáfilo. Hojas simples, linear-elípticas de hasta 1 cm de long con bordes enteros o dentados. Flores blancas o rosadas, urceoladas, solitarias o en cimas 2-3-floras y hediondas. Fruto cápsula tricoca, rojiza de 5 mm de diám. Florece en primavera y fructifica en verano.','Barrancas ribereñas y suelos arenosos-rocosos.','Endémica','Ornamental. Medicinal (antifebril). Flores polinizadas por moscas.'),
  (32,'Enterolobium contortisiliquum','(Vell.) Morong','Enterolobium','timbó colorado','oreja de negro','pacará','','','','Árbol','No','Alterna','Compuesta','Bipinnada','Entero','Blanco a verdoso','Seco','Fabaceae','Árbol de copa ancha, hemisférica y corteza grisácea de hasta 30 m de altura. Hojas compuestas, bipinnadas con 8-23 pares de foliolos subfalcados, lanceolados. Flores blancas dispuestas en capítulos hemisféricos de 10-20-floros, pedunculados en racimos axilares menores que las hojas. Fruto legumbre negra en círculo con forma reniforme.','Bosques ribereños, barrancas e islas.','Nativa','Ornamental. Medicinal (analgésico, tónico capilar y anticaspa, expectorante y antiblenorrágico). La madera es utilizada en mueblería y para diversos usos, especialmente tejuelas, revestimientos, interiores de embarcaciones, usos industriales etc. La corteza y los frutos contienen saponinas y sirven para lavar; por su contenido en taninos también para curtir. Melífera.'),
  (33,'Ephedra tweediana','Fisch. & C.A. Mey. emend. J.H.Hunz.','Ephedra','tramontana','pico de loro','cola de caballo','','','','Arbusto','No','Opuesta','Simple','Otra','Entero','Amarillo a anaranjado','Carnoso','Ephedraceae','Arbusto apoyante, trepador, dioico, de hasta 6 m de altura. Hojas simples, escuamiformes, de 2-5 mm de long., caducas. Estróbilos masculinos anaranjado-amarillento, generalmente sésiles, globosos de 4-7 mm de long. Estróbilos femeninos pedunculados, de 8-10 mm de long., brácteas carnosas, rojos con 2 semillas (raro 3). Semillas aovadas con cara ventral plana, castaño-oscuras, rugosas. Florece en primavera y verano.','Bosques ribereños, islas, matorrales y bosques semixerófilos.','Endémica','Ornamental. En medicina popular la infusión de los gajos, en tomas, es digestiva, diurética, antinefrítica, antirreumática, emoliente y astringente. El jugo de los frutos y de la decocción de la raíz, en tomas, son antiblenorrágicos, y la infusión de la raíz se bebe contra la sífilis; en cataplasmas, calma el dolor en casos de fracturas. Melífera.'),
  (34,'Erythrina crista-galli','L.','Erythrina','ceibo','zuinandí','seibo','','','','Árbol','No','Alterna','Compuesta','Trifoliada','Entero','Rojo a rosado','Seco','Fabaceae','Árbol de 4-10 m de altura, de madera blanda. Tronco de hasta 1 m diám. en la base; corteza resquebrajada, persistente. Ramas arqueadas con aguijones recurvos. Hojas caducas, trifoliadas, folíolos elípticos u ovados, enteros, glabros, de 3-11 cm. de long. Flores rojas en racimos hojosos. Fruto legumbre multiseminada, arqueada, de 10-20 cm long., castaño oscura. Semilla castaña, de forma más o menos cilíndrica. Florece de noviembre a febrero.','Pajonales y albardones, en bosques ribereños o formando “ceibales”, es decir bosques abiertos puros en el interior inundable de las islas.','Nativa','Ornamental. Declarada Flor Nacional de Argentina y de Uruguay. La madera tiene diversos usos (tarugos, colmenas, ruedas, esculturas, adoquines). Medicinal (Empleada como antiasmática, astringente, contra hemorroides, úlceras, rectitis, vaginitis blenorrágica y contra males del pecho). Semillas con alcaloides. De las flores se obtiene un colorante rojo usado para teñir tejidos.'),
  (35,'Escallonia megapotamica','Spreng. var. megapotamica','Escallonia','arbol del pito','pititos','','','','','Arbusto','No','Alterna','Simple','Espatulada','Dentado','Blanco a verdoso','Seco','Escalloniaceae','Arbusto de hasta 2 m de altura, con ramas rojizas. Hojas simples, alternas, espatuladas, obtusas, dentadas en su mitad superior, peciolo corto, acuminadas. Flores blancas, dispuestas en racimos. Fruto cápsula con estilo persistente, de 3 mm de long. Florece en primavera y fructifica en verano y otoño.','Bosque en galería, borde de ríos y arroyos, palmares.','Endémica','Ornamental. Melífera.'),
  (36,'Eugenia myrcianthes','Nied.','Eugenia','ubajay','','','','','','Árbol','No','Opuesta','Simple','Elíptica','Entero','Blanco a verdoso','Carnoso','Myrtaceae','Árbol o arbusto de hasta 10 m. de altura, muy ramificado de copa globosa. Hojas simples, pecioladas, aovado-oblongas o lanceoladas, acuminadas, de 3-6 cm de largo, pubescentes cuando jóvenes y glabras con la edad. Flores blancas, 5-6 meras, con el cáliz blanco tomentoso. Fruto drupa subglobosa o ligeramente alargada, amarillo-anaranjado, con indumento blanquecino de 3-6 cm de largo. Semilla globosa, de color marrón. Florece en primavera y fructifica en verano.','Frecuente en selvas marginales, montes ralos y terrenos arenosos.','Nativa','Ornamental. Frutos comestibles, se utilizan para preparar mermeladas y almíbares; en medicina popular son utilizados contra cálculos del riñón. Melífera.'),
  (37,'Eugenia uniflora','L.','Eugenia','ñangapirí','pitanga','','','','','Árbol','No','Opuesta','Simple','Ovalada','Entero','Blanco a verdoso','Carnoso','Myrtaceae','Árbol o arbusto, siempreverde, de 3 - 12 m. de altura. Hojas simples, opuestas, ovadas a oblongas, glabras, enteras, verde oscuras y lustrosas en el haz, pálidas en el envés, aromáticas, pecíolo muy corto, de 1,5 - 5 cm. de long. x 1 - 3 cm. de lat. Flores blancas, fragantes, pequeñas, en inflorescencias racimosas. Fruto baya globosa, anaranjada a roja. Semilla redonda, castaña. Florece en primavera y fructifica en verano.','En montes marginales, bosques ralos y selvas en galería.','Nativa','Ornamental. Medicinal (Infusión de las hojas para “dolores reumáticos”, analgésica, diurética, emenagoga, depurativa, digestiva, carminativa y antidiarreica). Fruto comestible. Combustible (leña y carbón). Aromática (Contiene aceites esenciales en tallos y hojas). Melífera.'),
  (38,'Eugenia uruguayensis','Cambess.','Eugenia','guayabo blanco','guaviyú','','','','','Árbol','No','Opuesta','Simple','Elíptica','Entero','Blanco a verdoso','Carnoso','Myrtaceae','Árbol de entre 5 y 12 m de altura, con copa amplia y corteza maculada. Hojas simples, subcoriáceas, opuestas, ovadas o elípticas de hasta 3,6 cm de long. Flores blancas, dispuestas en cortas umbelas, o raramente de forma solitaria. Fruto negro, semiperiforme, multiseminado, de 1 cm de long. Florece de noviembre a febrero.','Bosque ribereños.','Endémica','Ornamental. Medicinal (diurético, digestivo, antidiarreico). Utilizada para la construcción de postes y buen carbón. Melífera.'),
  (39,'Ficus luschnathiana','(Miq.) Miq.','Ficus','higuerón','agarra palo','','','','','Árbol','No','Alterna','Simple','Elíptica','Entero','Blanco a verdoso','Carnoso','Moraceae','Árbol de 10 a 25 m de altura, epifito y estrangulador, laticífero. Hojas simples, alternas, elípticas, de ápice subagudo a obtuso, de 6-15 cm de long., coriáceas y pecioladas. Flores unisexuales apétalas, pequeñas, dispuestas en el interior de un receptáculo cóncavo, globoso y sésil denominado sicono. La polinización de sus flores es entomófila, llevada a cabo por una pequeña avispa del género Blastophaga. Infrutescencias axilares conocidas como higos, pequeñas, de 1,5 mm long, globosas, amarillenta a la madurez. Aves frugívoras y murciélagos dispersan sus frutos y semillas. Florece en primavera y fructifica en verano.','Bosque ribereño y palmares.','Nativa','Ornamental. Madera útil para hacer cajones. Las infrutescencias “higos” son utilizadas para elaborar mermeladas. Medicinal (hojas en infusión usadas como purgante y vermífuga, el látex es usado externamente para cicatrizar heridas y llagas).'),
  (40,'Geoffroea decorticans','(Gillies ex Hook. & Arn.) Burkart','Geoffroea','chañar','','','','','','Árbol','Si','Alterna','Compuesta','Imparipinnada','Entero','Amarillo a anaranjado','Carnoso','Fabaceae','Árbol mediano o bajo, de 3-5 m de altura con tronco verdoso, irregular, con corteza exfoliante y ramas intrincadas, espinosas. Reproducción vegetativa por raíces gemíferas. Hojas imparipinnadas con 2-5 pares de folíolos, oblongos, el terminal mayor. Flores pequeñas en racimos cortos, corola amarilla con estrías rojas. Drupa globosa a ovoide, rojiza, glabra, lustrosa; con mesocarpio dulce. Semilla fusiforme de color marrón claro. Florece en primavera y fructifica en verano.','Bosques xerofíticos, ocupa campos altos, secos; en general forma colonias extensas de tamaño uniforme, de 2-3 m de alto.','Nativa','Madera blanda y liviana, útil en carpintería. Fruto comestible y forrajero, sirve para hacer dulce, arrope y obtención de harinas. Medicinal (Corteza y hojas en quemadillo contra la tos). Melífera.'),
  (41,'Gleditsia amorphoides','(Grisebach) Taubert.','Gleditsia','espina de corona','coronillo blanco','','','','','Árbol','Si','Alterna','Compuesta','Bipinnada','Dentado','Blanco a verdoso','Seco','Fabaceae','Árbol espinoso de 5 a 16 m de altura, con tronco recto cubierto de espinas en ramilletes horridos. Hojas compuestas, dimorfas, pinnadas o bipinnadas, fasciculadas o alternas de 15 a 20 cm de largo. Flores pequeñas, blanco-verdosas, dioicas dispuestas en racimos axilares y terminales de hasta 8 cm. de long. Fruto legumbre indehiscente de 5-9 cm de long., subfalcada de color negro lustroso. Semillas ovoides, comprimidas, castaño-oliváceas. Florece desde agosto a noviembre y fructifica a fines de primavera y verano.','Bosques ribereños, no muy común en Entre Ríos.','Nativa','Madera útil para leña y carbón vegetal. El fruto contiene tanino y saponinas, por lo que sirve para curtir y lavar. De la semilla se extrae mucílago utilizado en la industria como fijador para la fabricación de dulces, apresto de tejidos, papeles y en cosmética. Medicinal (hojas utilizadas contra la caspa). Fruto con valor forrajero. Melífera.'),
  (42,'Gleditsia triacanthos','L.','Gleditsia','acacia negra','espina de cristo','','','','','Árbol','Si','Alterna','Compuesta','Bipinnada','Dentado','Amarillo a anaranjado','Seco','Fabaceae','Árbol de 10 a 25 m de altura. Corteza grisácea, rugosa con espinas rojizas. Hojas compuestas, pinnadas y bipinnadas con foliolos opuestos, elíptico-ovados de 10 a 20 cm. Flores unisexuales, pequeñas, verdosa-amarillentas, dispuestas en racimos axilares subpendulos. Fruto legumbre negra-amarronada, linear-comprimida, recta o falcada de 15 a 40 cm de largo. Semillas castañas, elipsoides-comprimida. Florece en noviembre-diciembre y fructifica de diciembre a marzo.','Bosques ribereños, zonas bajas.','Introducida','Ornamental. Fruto forrajero y comestible, utilizado en la industria de dulces, farmacia y cosmética, ya que a partir de ellos se extrae una goma vegetal (garrofina) usada como espesante y fijador. Melífera. Medicinal (hojas son utilizadas para lavar el cabello y disminuir la caspa). Especie exótica invasora, originaria de Estados Unidos, de rápido crecimiento y alta tasa de reproducción.'),
  (43,'Guettarda uruguensis','Cham. & Schltdl.','Guettarda','palo cruz','jazmín del uruguay','','','','','Árbol','No','Opuesta','Simple','Ovalada','Entero','Blanco a verdoso','Carnoso','Rubiaceae','Arbusto, de 3 - 10 m. de altura, con ramas opuestas que forman una cruz. Hojas simples, opuestas, ovado-lanceoladas, pubescentes, enteras, de 4 - 9 cm. de long. x 2 - 4 cm. de lat. Flores blanco-rosadas, perfumadas, hermafroditas, pequeñas, agrupadas en cimas axilares largamente pedunculadas. El fruto es una drupa negra, elipsoide, carnosa, aterciopelada. Semilla lisa y recta. Florece de primavera a verano y fructifica de verano a otoño.','Crece en bosques ribereños, palmares y selvas marginales a orillas de ríos y arroyos.','Nativa','Ornamental. Madera empleada en construcciones rurales y mangos de herramientas. Medicinal (hojas utilizadas como astringente para lavar úlceras).'),
  (44,'Heimia salicifolia','(Kunth) Link','Heimia','quiebra arado','yerba de la vida','','','','','Arbusto','No','Verticilada','Simple','Elíptica','Dentado','Amarillo a anaranjado','Seco','Lythraceae','Arbusto de 1-3 m de altura, glabro. Hojas simples, sésiles, opuestas, decusadas o en verticilos trímeros, lanceoladas o elípticas, de 2-8 cm de long., discoloras, de borde ± recurvo, con nervio central manifiesto. Flores amarillas, solitarias, axilares, subsésiles. Fruto cápsula 4-locular, pluriseminada, encerrada por el tubo floral. Florece de primavera a verano y fructifica en verano.','Bosques ribereños, palmares, campos altos e inundables y bordes de caminos.','Nativa','Ornamental. Medicinal (la raíz y las hojas tienen propiedades laxantes y diuréticas). Melífera.'),
  (45,'Heteropterys glabra','Hook. & Arn.','Heteropterys','mariposita','tilo de campo','','','','','Arbusto','No','Opuesta','Simple','Ovalada','Entero','Amarillo a anaranjado','Seco','Malpighiaceae','Arbusto, de 1 - 3 m. de altura. Hojas simples, opuestas, enteras, ovadas, angostamente elípticas a lineares, con estipulas caedizas, de 2 - 11 cm. de long x 0,5 - 2,5 cm. de lat. Flores amarillas, zigomorfas, con limbo elíptico, reunidas en inflorescencias terminales generalmente en pseudorracimos o pseudoumbelas. Fruto di o tri sámara, rojizos castaños a la madurez, con ala dorsal desarrollada, obovada, diseminados por el viento. Florece en primavera-verano y fructifica en verano-otoño.','Frecuente en barrancas, suelos húmedos, en bordes del bosque en galería.','Nativa','Ornamental y para cercos vivos. Medicinal (Se utiliza como sedante).'),
  (46,'Hibiscus striatus','Cav.','Hibiscus','rosa del río','rosa del estero','','','','','Arbusto','Si','Alterna','Simple','Ovalada','Dentado','Rojo a rosado','Seco','Malvaceae','Arbusto de 1-2,5 m de altura, con frecuencia provisto de aguijones en tallos y pecíolos. Hojas simples, largamente pecioladas, ovadas, 3-5 lobuladas, aserradas. Flores rosadas con nervaduras más oscuras, solitarias, largamente pedunculadas, dispuestas en las axilas de las hojas superiores. Fruto cápsula hispida, castaña, multiseminada. Semilla negra, cubierta de pelos ásperos. Florece de primavera a otoño y fructifica de verano a invierno.','Matorrales, pajonales, zonas inundables y en orillas y albardones de ríos y arroyos.','Nativa','Ornamental. En medicina popular es empleado como pectoral y emoliente.'),
  (47,'Inga uraguensis','Hook. & Arn.','Inga','ingá','ingá colorado','','','','','Árbol','No','Alterna','Compuesta','Paripinnada','Entero','Blanco a verdoso','Seco','Fabaceae','Árbol, de 3 - 5 m. de altura, ramas con lenticelas en líneas transversales. Hojas compuestas paripinnadas, glabras o pubescentes con peciolo alado. Folíolos opuestos, elípticos o lanceolados. Flores blancas agrupadas en espigas axilares, solitarias o en pares a modo de plumerillo, capullos globosos. Fruto vaina afelpada, y bronceado tomentosa, con márgenes prominentes. Semillas elíptico-oblongas, castañas. Florece en primavera y fructifica en verano.','Común en los bosques en galería.','Endémica','Medicinal (la resina del fruto se utiliza para calmar dolores de caries, la corteza y hojas en infusión tienen acción astringente, expectorante y antineurálgica; hemostático y en uso externo cicatrizante). Madera útil en carpintería. Ornamental. El fruto es alimento de la fauna silvestre (Carpinchos, carayas, etc.).'),
  (48,'Jacaranda mimosifolia','D. Don','Jacaranda','jacarandá','','','','','','Árbol','No','Opuesta','Compuesta','Bipinnada','Entero','Azúl a púrpura','Seco','Bignoniaceae','Árbol de gran porte, con altura máxima de hasta 20 m. Corteza grisácea oscura, rugosa. Hojas compuestas, opuestas, decusadas, de 14-24 pares de pinnas primarias, dividida a su vez 10-30 pares de foliolos aovados-oblongos, agudos, mucronados. Flores azul-liláceas, tubulosas, dispuestas en amplias panojas terminales erguidas. Fruto cápsula leñoso-elipsoide, muy comprimida lateralmente. Semillas aladas. Florece en primavera-verano y fructifica en verano-otoño.','Dispersa en bosques ribereños y barrancas, poco frecuente.','Nativa','Ornamental. La madera se emplea en mueblería. Los frutos se utilizan en floristerías y artesanías. En medicina popular se emplea como antisifilítico, vulnerario, astringente, emoliente y anticonceptivo.'),
  (49,'Jodinia rhombifolia','(Hook. & Arn.) Reissek','Jodinia','sombra de toro','','','','','','Árbol','Si','Alterna','Simple','Otra','Entero','Blanco a verdoso','Carnoso','Cervantesiaceae','Árbol de 2-4 m de altura, muy ramificado. Hojas alternas, glabras, coriáceas, rómbicas, espinosas en los ángulos y ápice. Flores hermafroditas, reunidas en cimas axilares, perfumadas, protegidas en su base por brácteas pubescentes, carnosas, aovado-deltoideas. Fruto globoso, rojo, rugoso, que al madurar se desprende en sentido vertical, en 5 secciones, con el endocarpio leñoso constituyendo una cápsula drupácea. Semillas subesféricas de color blanco. Florece en otoño-invierno y fructifica de invierno a primavera.','Bosques xerófilos y también en bosques ribereños.','Nativa','Ornamental. La madera tiene aplicaciones caseras, y la corteza y el aceite extraído del fruto, propiedades curativas. Melífera.'),
  (50,'Lantana camara','L.','Lantana','lantana','camará','bandera española','','','','Arbusto','Si','Opuesta','Simple','Ovalada','Dentado','Amarillo a anaranjado','Seco','Verbenaceae','Arbusto de hasta 3 m de altura, con ramas rígidas inermes o con aguijones y tallo cuadrangular. Hojas simples ovado-oblongas, subcordadas, de margen crenado-serrado, áspera-escabrosas, opuestas de 2-9 cm. de long., pecioladas, de olor desagradable. Flores amarillas, anaranjadas y rojas de 10 mm de long., dispuestas en cabezuelas densas, hemisféricas, largamente pedunculadas, con brácteas lanceoladas. Fruto drupa esférica negra, carnosa, de 4 mm de diám. Florece en primavera-verano y fructifica en verano-otoño.','Bosque en galería y palmares.','Nativa','Ornamental. Medicinal en uso externo (El aceite esencial es antiinflamatorio, alivia los dolores reumáticos y artríticos). Planta tóxica para el ganado. Invasora en diversas partes del mundo.'),
  (51,'Ligustrum lucidum','W.T. Aiton','Ligustrum','ligustro','siempre verde','','','','','Árbol','No','Opuesta','Simple','Ovalada','Entero','Blanco a verdoso','Carnoso','Oleaceae','Árbol hasta de 4 a 12 m de altura. Corteza castaño grisácea, lisa y ramas con lenticelas. Hojas simples, opuestas, glabras, oval-lanceolada de bordes enteros y ápice acuminado, consistencia coriácea. Flores pequeñas blancas o blanco-cremosas, glabras dispuestas en panoja apical piramidal. Fruto baya ovoide-globosa, violácea casi negra. Semilla 1-2. Florece de octubre a febrero.','Bosque de ribera, palmares, matorrales, caminos vecinales.','Adventicia','Especie invasora, originaria de Asia. Ornamental. Melífera. En floración libera polen que provoca fiebre o asma en personas sensibles. Frutos tintóreos.'),
  (52,'Lippia alba','(Mill.) N.E. Br. ex Britton & P. Wilson var. alba','Lippia','salvia de la costa','salvia morada','','','','','Arbusto','No','Opuesta','Simple','Ovalada','Dentado','Azúl a púrpura','Seco','Verbenaceae','Arbusto aromático, de 1-1,5 m de altura, muy ramoso, pubescente. Hojas simples, opuestas o ternadas, aovadas o aovado-oblongas, cortamente pecioladas. Flores violácea o blanco-lilacina dispuestas en espigas cortas y densas, capituliformes, 1 o 2 por axila. Fruto esquizocárpico subgloso a ovoide, formado por dos mericarpios. Florece y fructifica en verano.','Frecuente en bosques ribereños y zonas bajas.','Nativa','Medicinal (Infusión de las hojas usada como digestiva, sedante, estimulante y antiespasmódica). Rica en aceites esenciales que son utilizados en la industria cosmética y farmacéutica. Melífera. Ornamental, por su follaje aromático.'),
  (53,'Lithraea molleoides','(Vell.) Engl.','Lithraea','molle de beber','aruera dura','molle blanco','aruera de quebradas','','','Árbol','No','Alterna','Compuesta','Imparipinnada','Entero','Amarillo a anaranjado','Carnoso','Anacardiaceae','Árbol resinoso, de 2 a 7 m de altura, ramas grisáceas. Hojas simples en los primeros años, luego compuestas, con 2 a 5 foliolos sésiles y alternos. Flores hermafroditas, pequeñas, amarillo-verdosas, dispuestas en panojas axilares. Fruto drupa globosa, blanquecina a verdosa. Florece en primavera y fructifica en verano.','Bosques ribereños, marginales y lugares abiertos.','Nativa','Ornamental. Melífera. Edulcorante. Medicinal (en medicina popular se utiliza en forma de infusión, decocción o extracto alcohólico para el tratamiento de la artritis, bronquitis, tos, y enfermedades del aparato digestivo, como antiinflamatorio, cicatrizante, emenagogo, antiespasmódico, antibacteriano y antifúngico, en casos de reumatismo o heridas se aplican como compresas o baños. También es diurético, hemostático, tónico, sedante, antimicrobiano, antiviral, citotóxico e inmunomodulador). Presenta sustancias alergógenas, que provoca dermatitis en personas sensibles.'),
  (54,'Lonchocarpus nitidus','(Vog.) Benth.','Lonchocarpus','yerba del bugre','lapachillo','','','','','Árbol','No','Alterna','Compuesta','Imparipinnada','Entero','Rojo a rosado','Seco','Fabaceae','Árbol de 5 a 8 m de altura, corteza gris plomiza y rugosa, ramas con lenticelas longitudinales. Hojas compuestas, imparipinnadas de 7 a 21 cm de long., dísticas, con grueso pulvínulo basal, de disposición alterna. Flores violáceas a rosado-blanco de 1-1,3 cm de long. dispuestas en racimos axilares rectos o erguidos. Fruto vaina de 4,5 a 10 cm de long., glabra, castaña, indehiscente. Semillas arriñonadas, de color naranja. Florece en verano y fructifica en otoño.','Bosque ribereño.','Nativa','Ornamental. Medicinal (la corteza en decocción se utiliza como astringente). Forestal, madera dura para usos locales en carpintería y tornería.'),
  (55,'Luehea divaricata','Mart.','Luehea','azota caballo','francisco álvarez','caá obeti','','','','Árbol','No','Alterna','Simple','Elíptica','Dentado','Rojo a rosado','Seco','Tiliaceae','Árbol heliófilo, de 5 - 15 m. de altura. Hojas alternas, cortamente pecioladas, elípticas u ovadas, verdes en la cara superior y afelpadas y blanquecinas en el envés, irregularmente dentado-serradas, de 2 - 9 cm. de lat. Flores rosado-liláceas con base amarilla, grandes, en cimas terminales y axilares. Fruto cápsula leñosa, ovoide, pubescente, grisáceo-verdosa, leñosa. Semillas pequeñas y aladas. Florece y fructifica desde verano a otoño.','Bosques ribereños, matorrales y lugares abiertos.','Nativa','Ornamental. Forestal, utilizada en carpintería. Medicinal (Corteza en cocimiento antirreumática y en infusión astringente y depurativo; hojas en cocimiento en uso interno antiinflamatorias, estomáquicas y febrífugas, y flores astringentes en infusión en casos de irritaciones de útero y deposiciones sanguinolentas).'),
  (56,'Manihot grahamii','Hook.','Manihot','falso café','falsa mandioca','mandioca cimarrona','mandioca brava','','','Árbol','No','Alterna','Simple','Palmatilobada','Entero','Blanco a verdoso','Seco','Euphorbiaceae','Árbol de 2 a 5 metros de altura, con corteza cenicienta y látex. Hojas simples, alternas, palmatipartida con 5-13 lóbulos de 5-20 cm. de longitud y pecíolo largo. Flores amarillentas dispuestas en panículas compuestas, las estaminadas con manchas violetas en su interior y cáliz campanulado. Fruto capsular, tricoco, granuloso-áspero de hasta 1,8 cm long. Semillas lisas, grisáceas-parduzcas con máculas vinosas, carunculadas de 11 mm de long. X 7-8 mm de lat. Florece en verano y fructifica en verano-otoño.','Borde de arroyos y bosques en galerías.','Nativa','Ornamental. Madera y semillas utilizadas para fabricar artesanías. Medicinal (las hojas en aplicaciones externas son usadas como febrífugas y fungicidas). Semillas tóxicas.'),
  (57,'Maytenus ilicifolia','Mart. ex Reissek','Maytenus','congorosa','','','','','','Arbusto','No','Alterna','Simple','Elíptica','Dentado','Amarillo a anaranjado','Carnoso','Celastraceae','Arbusto de hasta 5 m de altura. Hojas simples de 2 a 4 cm. de longitud, alternas, elípticas, coriáceas de borde marginado, ondeado, con dientes espinosos y borde amarillo. Flores verdes-amarillentas, pequeñas en fascículos axilares. Fruto cápsula obovoide, bivalva, rojiza. Semillas de 1-4 cubiertas por un arilo rojizo. Florece en septiembre y a fines de invierno.','Bosques ribereños, matorrales y palmares.','Nativa','Ornamental. Usada para realizar artesanías. Medicinal (Analgésica, Estomacal, Antiasmática, Bactericida, Diurética, Anticancerosa, Antiinflamatoria, Antipéptica, Depurativa, Antiulcerogénica, Anticonceptiva).'),
  (58,'Melia azedarach','L.','Melia','paraíso','','','','','','Árbol','No','Alterna','Compuesta','Imparipinnada','Dentado','Azúl a púrpura','Carnoso','Meliaceae','Árbol de copa globosa, tronco muy rugoso, de hasta 10 metros de altura. Hojas compuestas, alternas, 2-3 imparipinadas, con foliolos, aovados, agudos, aserrados, de 2,5 cm. de largo, glabros. Flores violáceas, perfumadas, de más o menos de 1,5-2 cm. de diám., dispuestas en panojas. Fruto drupa globosa, amarilla u ocrácea de 1,5-2,5 cm. de largo. Semillas ovaladas, de color negro y 7 mm de diám. Florece en primavera y fructifica en verano-otoño.','Bordes de matorrales y tierras altas.','Adventicia','Especie exótica de rápido crecimiento, originaria de Asia; subespontánea e invasora en varias regiones del mundo. Ornamental. Melífera. Insecticida: los frutos, flores, hojas y corteza presentan dos alcaloides, paraisina y azadiractina. Frutos y semillas tóxicos. La madera se usa para leña, mangos para herramientas muebles y ebanistería, juguetes, etc. Medicinal (La corteza en aplicaciones externas es utilizada como antimicótica).'),
  (59,'Mimosa pigra','L. var. pigra','Mimosa','carpinchera','sensitiva','yuquerí','','','','Arbusto','Si','Alterna','Compuesta','Bipinnada','Entero','Rojo a rosado','Seco','Fabaceae','Arbusto de 1,5-4 m de altura, ramoso, con cerdas hirsutas marrón-bronceadas y aguijones recurvos. Hojas compuestas, paribipinnadas, alternas de 4-26 cm de largo, raquis con aguijones recurvos, sensitivas al tacto o al caer la noche. Flores bisexuales desde verdosa blanquecina a rosado, dispuestas en capítulos axilares pedunculados ovoides. Fruto legumbre plana segmentada, marrón, densamente hispida que se desarticula en artejos a la madurez. Semilla lisa, oblongo-elipsoides de color castaño oliváceas. Florece en primavera y verano. Diseminación por hidrocoria y zoocoria.','Borde de arroyos, ríos, zonas bajas e islas.','Nativa','Ornamental, para cercos. Medicinal (raíz hojas utilizadas como vulnerario y purgante). Melífera.'),
  (60,'Mimosa uraguensis','Hook. & Arn.','Mimosa','mimosa','','','','','','Arbusto','Si','Alterna','Compuesta','Bipinnada','Entero','Rojo a rosado','Seco','Fabaceae','Arbusto, ramoso, de 1 - 3 m. de altura. Ramitas rojizas, lisas, aguijones dispersos, rectos. Hojas compuestas; folíolos aproximados. Flores rosadas dispuestas en capítulos globosos. Fruto lomento lineal comprimido, glabro, oscuro. Florece durante primavera-verano y fructifica en verano.','En la ribera del río Uruguay y sus afluentes','Endémica','Ornamental. Melifera, puede utilizarse como seto vivo.'),
  (61,'Morus alba','L.','Morus','mora','','','','','','Árbol','No','Alterna','Simple','Ovalada','Dentado','Blanco a verdoso','Carnoso','Moraceae','Árbol de porte mediano, con látex, ramitas pubescentes y copa globosa. Hojas simples, alternas, groseramente dentadas, anchamente aovadas, cordadas, densamente pubescentes en la cara inferior, de 5-20 cm. de largo. Flores verdosas, masculinas dispuestas en racimos alargados, las femeninas en inflorescencias capituliformes. Infrutescencia carnosa (sorosio) de 2-2,5 cm. de longitud, blanca, rosa o hasta morada. Florece en primavera y fructifica en primavera y verano.','Bosques ribereños, zonas inundables, sitios degradados, borde de arroyos.','Adventicia','Originaria del centro este de China, invasora. Ornamental. Frutos comestibles, frescos o en mermeladas. Las hojas son utilizadas para alimentar gusanos de seda y ganado doméstico. Madera utilizada para la fabricación de instrumentos, carpintería, implemento para agricultura. Hojas y frutos empleados para teñir. Medicinal (corteza usada internamente como laxante, vermífugo, antitusivo, expectorante y diurético, externamente como antimicótico).'),
  (62,'Myrceugenia glaucescens','(Cambess.) D. Legrand & Kausel','Myrceugenia','murta','multa','','','','','Árbol','No','Opuesta','Simple','Elíptica','Entero','Blanco a verdoso','Carnoso','Myrtaceae','Árbol, muy ramificado, de 3 - 6 m. de altura. Hojas simples, opuestas, oblanceoladas, enteras, discoloras, de 2,5 - 8 cm. de long. x 0,5 - 2,5 cm. de lat. Flores blancas, fragantes, dispuestas en fascículos axilares de 2 - 3 flores. Fruto baya elipsoide u ovoide, amarilla, roja o negra de acuerdo a la madurez. Semilla 1-4 por fruto. Florece en primavera-verano y fructifica en verano-otoño.','Frecuente en los matorrales ribereños, bosques ribereños, palmares.','Nativa','Ornamental. Medicinal (Hojas digestivas, antidiarreico en cocimiento). Madera útil para leña. Melífera.'),
  (63,'Myrcia selloi','(Spreng.) N. Silveira var. selloi','Myrcia','guayabo amarillo','guayabo overo','guaminí','cambuí','','','Árbol','No','Opuesta','Simple','Elíptica','Entero','Blanco a verdoso','Carnoso','Myrtaceae','Árbol de 2,5 - 5 m. de altura. Hojas simples, elípticas, elíptico-oblongas u ovado-oblongas, de 1,5 - 5,5 cm. de long. x 0,8 - 3 cm. de lat. Panículas con 4 - 15 flores pediceladas, fragantes. Fruto globoso, rojo. Semillas 1-2 por fruto. Florece y fructifica en verano.','En suelos arenosos o pedregosos, en montes marginales y selvas en galería.','Nativa','Fruto comestible. Ornamental. Melífera.'),
  (64,'Myrcianthes cisplatencis','(Cambess.) O. Berg','Myrcianthes','guayabo colorado','mato','arrayán','arazá de monte','','','Árbol','No','Opuesta','Simple','Elíptica','Entero','Blanco a verdoso','Carnoso','Myrtaceae','Árbol de 2 - 8 m. de altura, corteza exfoliante y lisa. Hojas simples, enteras, lanceoladas, opuestas, elípticas o angostamente ovadas, de 1,5 - 6 cm. de long. x 0,5 - 1,5 cm. de lat. Flores blancas, reunidas en grupos de a 3, muy perfumadas, pequeñas. Fruto baya carnosa, pequeña, negro violáceo. Semillas de color castaño, 1-2 por fruto. Florece durante primavera-verano y fructifica en verano.','En bosques, selvas en galería, matorrales y bosque parque, asociada a los cursos de agua.','Endémica','Ornamental. Medicinal (Hojas, frutos y sumidades utilizadas como tónico, astringente, estimulante y diurético). Melífera.'),
  (65,'Myrcianthes pungens','(O. Berg) D. Legrand','Myrcianthes','arrayán','guabirá','guabiyú','mato blanco','','','Árbol','No','Opuesta','Simple','Elíptica','Entero','Blanco a verdoso','Carnoso','Myrtaceae','Árbol de hasta 20 m de altura, corteza lisa con manchas claras. Hojas simples, discoloras, elípticas a ovadas con ápice punzante, pecioladas, de consistencia coriácea. Flores blancas, delicadas y solitarias o agrupadas en racimos. Fruto baya globosa, glabra, violácea, de 1 cm de diám. Semilla reniforme. Florece de octubre a noviembre y fructifica en enero.','Bosques ribereños e islas.','Nativa','Ornamental. Fruto comestible. Melífera. Medicinal (hojas con propiedades diaforéticas y diuréticas). Madera útil para carpintería.'),
  (66,'Myrrhinium atropurpureum','Schott var. octandrum Benth.','Myrrhinium','palo de fierro','lata','maitín','piojo de chancho','socará','','Árbol','No','Opuesta','Simple','Elíptica','Entero','Rojo a rosado','Carnoso','Myrtaceae','Árbol de hasta 5 m de altura, con corteza oscura y persistente. Hojas simples, opuestas, lanceoladas y cartáceas de hasta 8 cm. de long. Flores pequeñas con pétalos carnosos blanquecinos y estambres rojizos, dispuestas en cimas corimbosas sobre las ramas. Fruto baya ovoide de 1 mm de long, negro a la madurez. Semillas subreniformes. Florece a fines de invierno-principio de primavera y fructifica en verano-otoño.','Bosque ribereño.','Nativa','Ornamental. Melífera. Produce buena leña y carbón. Madera utilizada para tallar artesanías.'),
  (67,'Myrsine laetevirens','(Mez) Arechav.','Myrsine','canelón','canelón hembra','canelón morotí','palo de San Antonio','capororoca','','Árbol','No','Alterna','Simple','Espatulada','Entero','Blanco a verdoso','Carnoso','Primulaceae','Árbol de hasta 8 m de altura, con corteza rugosa. Hojas simples, verdosas, con muchos puntos negros u oscuros en ambas caras o en la inferior; pero pocas o ninguna raya. Flores blanquecinas en racimos axilares o laterales con breves pedúnculos y raquis juntos de 3-5 mm de long. Fruto drupa violácea, uniseminada. Semilla parda. Florece en primavera y fructifica en verano.','Boques ribereños, de barranca y en los albardones internos.','Nativa','Ornamental, recomendable para sombra. Medicinal (empleado en medicina popular para el tratamiento del reuma, dolores lumbares y fracturas). Melífera.'),
  (68,'Nectandra angustifolia','(Schrad.) Nees & Mart.','Nectandra','laurel de río','laurel amarillo','laurel mini','','','','Árbol','No','Alterna','Simple','Lineal','Entero','Amarillo a anaranjado','Carnoso','Lauraceae','Árbol de hasta 12 m de altura, con ramas cilíndricas. Hojas simples y alternas, falcadas, linear lanceoladas a oblongas de 3-17 x 0,2-1,7 cm con ápice acuminado. Flores blanco amarillentas de 6-8 mm de diámetro, dispuestas en panículas axilares en el extremo de las ramas. El fruto es una baya elipsoide, de color castaño claro con manchas verde oscuras de 12 a 18 mm de largo. Semilla de 1 cm. de largo. Florece en invierno y fructifica en primavera.','Lugares húmedos, bosque en galería, en borde de ríos e islas.','Endémica','Melífera. Forestal. Utilizada en medicina popular como alexítera (en accidentes ofídicos).'),
  (69,'Ocotea acutifolia','(Nees) Mez','Ocotea','laurel blanco','ayuí-morotí','laurel criollo','laurel negro','laurel blanco','canela','Árbol','No','Alterna','Simple','Elíptica','Entero','Amarillo a anaranjado','Carnoso','Lauraceae','Árbol de hasta 20 m de altura. Ramas cilíndricas, con lenticelas escasas. Hojas simples, alternas, lanceolado a elíptico de 4 a 14 cm de long. X 1-4,5 cm lat. con ápice acuminado, peciolo hasta de 25 mm de largo. Flores amarillentas, pequeñas, imperfectas, pequeñas dispuestas en panojas axilares o subterminales. Fruto baya de elipsoide a ovoide, de 2 cm, de color morado oscuro con cúpula discoidal plana. Florece en primavera-verano y fructifica en verano.','Bosque en galería, márgenes de los ríos e islas.','Nativa','Madera utilizada en carpintería para la confección de muebles, tirantes, cajones y colmenas. Sus ramas contienen saponinas. Medicinal (hojas en infusión usadas como estomacales).'),
  (70,'Parkinsonia aculeata','L.','Parkinsonia','cina cina','','','','','','Árbol','Si','Alterna','Compuesta','Bipinnada','Entero','Amarillo a anaranjado','Seco','Fabaceae','Árbol de 3-6 m de altura, con corteza lisa, verdosa-azulada y ramas espinosas y péndulas. Hojas compuestas, bipinnadas con raquis primario corto, espinoso y raquis secundarios largos y planos con numerosos foliolos caducos. Flores vistosas y fragantes, de color amarillo con manchas rojas, dispuestas en racimos solitarios axilares. Fruto legumbre linear, recta, indehiscente, con 2 a 6 semillas. Semilla oval, de color negruzco. Florece en primavera-verano y fructifica en verano.','Campos bajos, matorrales, bosque parque y borde de bosque en galería.','Nativa','Melífera. Ornamental (cultivada para formar cercos vivos). Madera usada para postes, cercas, construcciones rurales. Del tronco se obtiene pulpa para pasta de papel y por incisiones se extrae una goma similar a la arábiga. Semillas comestibles. Medicinal (se emplea como abortiva, febrífuga, diaforética, antirreumática, antipalúdica y sudorífica).'),
  (71,'Pavonia sepium','A. St.-Hil. subsp. sepium','Pavonia','malva del bosque','malvavisco de cerco','','','','','Arbusto','No','Alterna','Simple','Ovalada','Dentado','Amarillo a anaranjado','Seco','Malvaceae','Arbusto, de 1 - 1,50 m. de altura. Hojas simples, oval-lanceoladas, aserradas, haz glabro, envés con pelos estrellados planos, hasta 9 cm. de long. x 4 cm. de lat. Flores amarillas, solitarias. Fruto esquizocarpo con mericarpios trígonos, con 3 aristas largas, cubiertas de pelos retrorsos. Semilla glabra. Florece en primavera-verano y fructifica en verano-otoño.','Común en bosques en galería.','Nativa','Ornamental. Medicinal (Hojas usadas como emoliente y pectoral).'),
  (72,'Phyllanthus sellowianus','(Klotzsch) Müll. Arg.','Phyllanthus','sarandí blanco','sarandí','','','','','Arbusto','No','Alterna','Simple','Elíptica','Dentado','Blanco a verdoso','Seco','Phyllanthaceae','Arbusto monoico, de 1,5 - 5 m. de altura, glabro, con látex. Hojas simples, alternas, discoloras, elíptico-lanceoladas, cortamente pecioladas, enteras, de 1,5 - 5 cm. de long. x 0,5 a 1 cm. de lat. Flores verdosas, unisexuales, pequeñas, apétalas, en fascículos axilares. Fruto cápsula tricoca, deprimido-globosa, castaña. Semilla trígona, lisa. Florece en primavera y fructifica en verano.','Crece en matorrales ribereños, terrenos bajos inundables.','Endémica','Ornamental. Medicinal (Hojas en cocimiento antiasmáticas, diuréticas y purgantes, leño y hojas potentes antidiabéticos, ligeramente laxantes y emenagogos).'),
  (73,'Phytolacca dioica','L.','Phytolacca','ombú','','','','','','Árbol','No','Alterna','Simple','Elíptica','Entero','Blanco a verdoso','Carnoso','Phytolaccaceae','Árbol dioico de 8-12 m de altura, frondoso, de copa globosa y tronco muy grueso y flojo con estructura secundaria anormal. Hojas simples, coriáceas, glabras, con lamina foliar elíptica u ovada, aguda, acuminada o subrotunda con nervio medio prominente en la cara abaxial. Flores amarillenta, unisexuales dispuestas en racimos péndulos, terminales o pseudolaterales. Baya múltiple, subglobosa, meloniforme, ligeramente compresa y deprimida, verdoso-amarillenta. Semillas ovoides. Florece en verano y fructifica en otoño.','Bosques subxerófilos y barrancas marginales.','Nativa','Ornamental. Medicinal (en medicina popular las hojas se usan para lavar y curar heridas, como purgante. La raíz en cocimiento se bebe como antirreumática, y en aplicación externa las cenizas de la corteza obran como antiséptico, astringente y vulnerario). Las cenizas contienen gran cantidad de potasa que se emplea en la fabricación casera de jabón. Melífera.'),
  (74,'Plinia rivularis','(Cambess.) Rotman','Plinia','vaporetí','baporetí','guabiyú','ibaporoití','','','Árbol','No','Opuesta','Simple','Elíptica','Entero','Blanco a verdoso','Carnoso','Myrtaceae','Árbol mediano, de hasta 12 m de altura, glabro. Hojas simples, pecioladas, de 5-7 cm de long. y 1,3 a 3,4 cm de lat., opuestas, oval oblongas, concoloras con ápice acuminado. Flores blancas, dispuestas en racimos axilares laxos. Fruto baya globosa oscura a la madurez. Florece en primavera y fructifica en verano.','Bosques ribereños de los ríos Uruguay y Cuareim.','Nativa','Ornamental. Fruto comestible. Melífera. Medicinal (la corteza en infusión es utilizada contra la inflamación estomacal).'),
  (75,'Porlieria microphylla','(Baill.) Descole, O’ Donell & Luorteig','Porlieria','rama crispa','cucharero','','','','','Arbusto','No','Opuesta','Compuesta','Paripinnada','Entero','Blanco a verdoso','Seco','Zygophyllaceae','Arbusto de 3-4 m de alt., con ramas rectas y corteza rugosa. Hojas compuestas, pubescentes, paripinnadas, con 6-13 pares de folíolos oblongos, asimétricos; estípulas negruzcas espinescentes. Flores pequeñas, blanco amarillenta, solitarias, tetrámeras. Frutos negros subglobosos. Semillas subreniformes, negras. Florece en primavera y fructifica en verano.','Poco frecuente, en barrancas marginales.','Nativa','Ornamental. Medicinal (corteza utilizada como antisifilítico, para dolores reumáticos y vulnerario).'),
  (76,'Pouteria gardneriana','(A. DC.) Radlk.','Pouteria','aguay-guazú','mata ojos colorado','aguaí','','','','Árbol','No','Alterna','Simple','Elíptica','Entero','Blanco a verdoso','Carnoso','Sapotaceae','Árbol de 5-15 m de altura. Corteza grisácea, surcada longitudinalmente. Ramas con yemas rojizo estrigosas. Hojas simples, alternas, oblongo-oblanceoladas, linear lanceoladas, aproximadas por los entrenudos breves. Flores pequeñas, blanco-verdosas, fragantes, dispuestas en umbelas laterales sésiles. Baya globosa o piriforme, carnosa, lisa, aromática, anaranjado-rojiza de 3-5 cm. de long. Semilla grande, ovoide, con ancha cicatriz longitudinal. Florece en octubre y noviembre. Fructifica desde enero a abril.','Bosque ribereño e islas.','Nativa','Madera valiosa, utilizada en tornería. Fruto comestible, utilizado para preparar conservas y mermeladas. Melífera.'),
  (77,'Pouteria salicifolia','(Spreng.) Radlk.','Pouteria','mata ojo','','','','','','Árbol','No','Alterna','Simple','Lineal','Entero','Blanco a verdoso','Carnoso','Sapotaceae','Arbusto o árbol, de 3 - 15 m. de altura. Corteza parda agrietada longitudinalmente. Hojas simples, alternas, linear-lanceoladas, enteras, subglabras, lustrosas, de 8 - 20 cm. de long. Flores blanco-amarillento-verdosas con perfume a violetas, pequeñas, sésiles, en fascículos axilares. Fruto verdoso hasta rojizo al madurar, semiseco, ovoide, con apéndice apical largo, en general encorvado. Semilla única, suelta, ovoide, gruesa. Florece en verano y fructifica en verano-otoño.','Frecuente en bosques en galería, márgenes de ríos y arroyos e islas.','Endémica','Ornamental. Fruto comestible. Medicinal (Resina: vulnerario). Su madera, al ser quemada, libera un humo denso, que produce fuerte ardor en los ojos, siendo muy bueno para espantar insectos. Melífera.'),
  (78,'Prosopis affinis','Spreng.','Prosopis','ñandubay','','','','','','Árbol','Si','Alterna','Compuesta','Bipinnada','Entero','Amarillo a anaranjado','Seco','Fabaceae','Árbol de 3-8 m de alto, de copa aparasolada, irregular, corteza rugosa y ramas largas, extendidas con espinas geminadas. Hojas compuestas, bipinnadas, folíolos 10-25 pares pequeños, coriáceos, marcadamente pinnatinervados. Flores pequeñas, hermafroditas, amarillentas, puberulas, dispuestas en racimos espiciformes. Fruto legumbre, arqueada en forma de hoz, de color amarillo pajizo con manchas violáceas. Semillas ovaladas y comprimidas. Florece desde septiembre a enero, y fructifica en verano.','Bosques xerófilos, es una especie característica del Espinal. Ocasionalmente se la ha registrado próxima a bosques ribereños y en bosque parque.','Nativa','Melífera. Medicinal (corteza, raíz y hojas utilizadas como astringente, en lavados se usa para quemaduras). Madera utilizada para postes de alambrado y carbón de leña, siendo de la mejor calidad. Frutos forrajeros.'),
  (79,'Prosopis nigra','(Griseb.) Hieron. var. nigra','Prosopis','algarrobo negro','algarrobo','','','','','Árbol','Si','Alterna','Compuesta','Bipinnada','Entero','Amarillo a anaranjado','Seco','Fabaceae','Árbol corpulento con la edad, de 3 a 16 m de altura; copa hemisférica de ramitas largas, tenues, flexuosas, arqueadas y péndulas., inerme o poco espinoso. Hojas compuestas, bipinnadas, con 12-25 pares de folíolos opuestos, elíptico-ovalados, glabros. Flores amarillentas, pequeñas, corola casi glabra, adentro vellosa, dispuestas en racimos espiciformes axilares péndulos. Fruto lomento drupáceo de pulpa dulce, falcado, manchado de violáceo oscuro. Florece de septiembre a noviembre y fructifica en verano.','Bosques xerófilos y blanquizales.','Nativa','Ornamental. Melífera. La madera tiene varios usos en carpintería, se usa para muebles y tienes propiedades tánicas por lo cual es utilizada en el curtido de cueros y para teñir telas. El fruto, en algunas provincias, se usa para hacer harina, patay y bebidas como la chicha, aloja, añapa. Medicinal (el humo del fruto es utilizado contra el asma, hoja y corteza astringente, frutos antioftálmicos).'),
  (80,'Psidium salutare','(Humb., Bonpl. & Kunth) O. Berg var. sericeum (Cambess.) Landrum','Psidium','arazá rastrero','arazá blanco','alpa mato','','','','Arbusto','No','Opuesta','Simple','Ovalada','Entero','Blanco a verdoso','Carnoso','Myrtaceae','Arbusto seríceo con raíz leñosa (xilopodio). Hojas simples, pubescentes, oblongo-lanceoladas, sésiles, discoloras. Flores blancas, solitarias con pedúnculo pubescente, dispuestas en las axilas de las hojas. Fruto baya pubescente de hasta 2 cm. de diám. Florece y fructifica en verano.','Suelos arenosos y afloramientos rocosos, palmares.','Nativa','Ornamental. Medicinal (hojas vulnerarias, se emplean en uso externo contra enfermedades de la piel; tisana de raíz y frutos verdes astringente).'),
  (81,'Psychotria carthagenensis','Jacq.','Psychotria','naranjillo','jazmín de la costa','','falso café','','','Arbusto','No','Opuesta','Simple','Elíptica','Entero','Blanco a verdoso','Carnoso','Rubiaceae','Arbusto rizomatoso que puede llegar a alcanzar los 4 m de altura. Hojas simples, opuestas, elípticas de ápice agudo de hasta 16 cm de largo y estipulas caedizas. Flores pentámeras, pequeñas de color blanco, sésiles, dispuestas en inflorescencias terminales laxas, pedunculadas. Fruto drupáceo, de morado a rojo brillante a la madurez. Semillas con 4-6 costillas. Florece en primavera y verano, fructifica en otoño, invierno y primavera.','Bosques ribereños, costa del río.','Nativa','Ornamental. Medicinal (con propiedades fúngicas y antibacterianas).'),
  (82,'Ricinus communis','L.','Ricinus','tártago','ricino','','','','','Arbusto','No','Alterna','Simple','Palmatilobada','Dentado','Rojo a rosado','Seco','Euphorbiaceae','Arbusto monoico de 2-3 m de altura. Hojas simples, palmatipartidas de 10 a 40 cm. de diám. con lóbulos elípticos, irregularmente dentados, de color verde, verde-grisáceo o rojiza y con peciolo tan largo como las láminas. Flores dispuestas en inflorescencias terminales, racemiformes, las masculinas amarillentas, presentes en la parte basal de la inflorescencia y flores femeninas rojizas, ovario densamente cubierto por largos tubérculos blandos, que parecen pelos gruesos ubicadas en la parte apical de la inflorescencia. Frutos cápsulas subglobosas equinadas, trilobadas. Semillas carunculada, grande, de 1 a 1,5 cm, y jaspeadas de color marrón y blanco, de superficie lisa y brillante. Florece en verano y fructifica en otoño-invierno.','En bordes de arroyos y bosques, caminos, zonas bajas, y ambientes disturbados.','Adventicia','Especie originaria de África que se comporta como invasora. Semilla tóxica, por la presencia de ricina. Industrialmente, de la semilla se extrae el aceite de castor de uso en pinturas, barnices, lubricantes, etc, como biodiesel y farmacéutico. Medicinal (aceite de semillas purgante y tónico, hojas en aplicaciones externas, como cataplasmas, cicatrizantes y refrigerantes; raíz en decocción útil contra cólicos). Ornamental. El polen puede ocasionar alergias respiratorias.'),
  (83,'Ruprechtia laxiflora','Meisn.','Ruprechtia','viraró crespo','marmelero','ibirapyta-í','ibirápi-hú','viraró colorado','viraró','Árbol','No','Alterna','Simple','Elíptica','Entero','Blanco a verdoso','Seco','Polygonaceae','Árbol de hasta 20 m de altura., con corteza gris oscura, agrietada longitudinalmente. Hojas simples, ovado-lanceoladas o elípticas de 2 a 7 cm de long. con ápice acuminado y peciolo breve pubérulo, verde lustroso. Flores dispuestas en racimos con pedicelos articulados y ócrea, las masculinas de 2 mm de long., apétalas, blanco verdosas y las femeninas de 3-4 mm de long. con tépalos sepaloides de color rojizo- amarillento. Fruto aquenio elipsoide, trígono, castaño lustroso. Semillas subovoide, trígona. Florece y fructifica en verano.','Bosques ribereños e islas.','Nativa','Ornamental. Forestal, madera útil y de calidad en mueblería. Medicinal (hojas y corteza utilizadas como astringentes, la infusión de las hojas es antidiarreica). Melífera.'),
  (84,'Ruprechtia salicifolia','(Cham. et Schlecht.) C. A. Mey','Ruprechtia','viraró','ibiraró','viasco','ibirá pitá','sarandí negro','mata negra','Árbol','No','Alterna','Simple','Elíptica','Entero','Blanco a verdoso','Seco','Polygonaceae','Árbol de 2 a 5 m de altura, de corteza grisácea. Hojas simples, alternas, elípticas-lanceoladas, agudas en el ápice, subcoriácea, de 3 a 12 cm de long. brillantes, con peciolo breve y ócreas en los nudos efímeras. Flores pequeñas, unisexuales, las masculinas dispuestas en panojas terminales o axilares y las femeninas en racimos. Fruto aquenio trígono de 8 mm de long., castaño, cubierto por 3 sépalos acrescentes vistosos. Semilla oblonga. Florece en primavera y fructifica en verano.','Bosque en galería.','Endémica','Ornamental. Forestal, excelente madera, útil en carpintería, mueblería y ebanistería. Melífera.'),
  (85,'Salix humboldtiana','Willd.','Salix','sauce criollo','','','','','','Árbol','No','Alterna','Simple','Lineal','Dentado','Amarillo a anaranjado','Seco','Salicaceae','Árbol de 10-15 m de alt., dioico, inerme, de ramas erguidas y extendidas. Hojas simples, alternas, linear-lanceoladas, cortamente pecioladas, finamente aserradas. Inflorescencia en amentos terminales, flores verde-amarillentas, masculinas con brácteas y filamentos lanuginosos y femeninas con ovario sésil y estilo bífido. El fruto es una cápsula multiseminada, dehiscente por dos valvas. Semillas rodeadas por abundantes pelos blancos y algodonosos. Florece a fines de invierno y en primavera, fructifica en primavera.','Común en islas y riberas de ríos.','Nativa','Ornamental. Madera apta para la confección de fósforos, cajones, etc. Artesanal. Medicinal (contiene salicilatos, base de la preparación de las aspirinas y disolventes del ácido úrico; en medicina popular la corteza es utilizada como astringente, analgésica, antirreumática, sedativa, febrífuga y las hojas licuadas con leche para la bronquitis, en decocción para otorgar brillo al cabello). La corteza contiene taninos y un alcaloide llamado salicilína, sucedáneo de la quinina y resinas. Las hojas hervidas con shampoo dan brillo al cabello. Melífera, productora de propóleos.'),
  (86,'Sapium haematospermun','Mull. Arg.','Sapium','curupí','lecherón','','','','','Árbol','No','Alterna','Simple','Lineal','Dentado','Blanco a verdoso','Carnoso','Euphorbiaceae','Árbol monoico de 8-10 m de alt., con corteza lisa, blanquecina, con látex lechoso. Hojas elípticas u oblongas, glabras de 7-20 cm. de long.; pecíolo breve; estípulas persistentes, triangulares. Flores amarillentas apétalas en inflorescencias terminales; brácteas con 2-11 flores estaminadas, cupuliformes; las flores pistiladas solitarias en las axilas de las brácteas. Fruto ± globoso, liso, capsular. Semillas totalmente cubiertas por un arilo carnoso y rojo. Florece en primavera y fructifica en verano.','En la región crece en bosques ribereños, matorrales, palmares y pajonales.','Nativa','Ornamental. La madera tiene aplicación local en carpintería y en la fabricación de muebles, esculturas y violines. Medicinal (el látex es usado en medicina popular para curar el dolor de muelas y como vulnerario, febrífugo, antiodontálgico y contra el reumatismo crónico, gota y neuralgias). Tiene apreciable cantidad de caucho. La corteza es utilizada para teñir tejidos de amarillo y curtir cueros, de ella se extraer el látex para fabricar la pega pega (pegamento casero). Melífera.'),
  (87,'Schaefferia argentinensis','Speg.','Schaefferia','abaticú','','','','','','Árbol','No','Alterna','Simple','Ovalada','Entero','Blanco a verdoso','Carnoso','Celastraceae','Árbol de 1,5-4 m de altura., glabro. Ramas delgadas, estriadas. Hojas simples, anchamente lanceoladas u ovadas, de 1,5-7 cm. long. x 1-4 cm. de lat. Flores pequeñas, pedunculadas y verdosas, dispuesta de forma axilar. Fruto globoso, ovoide, anaranjado, de 4 mm de long. con 2 semillas. Florece en primavera y fructifica en verano.','Bosque en galería y en barrancas.','Endémica','Ornamental. Melífera.'),
  (88,'Schinus longifolia','(Lindl.) Speg. var. longifolia','Schinus','molle','','','','','','Árbol','Si','Alterna','Simple','Espatulada','Entero','Blanco a verdoso','Carnoso','Anacardiaceae','Árbol de 4-10 m de alto con ramas espinescentes. Hojas alternas oblongas, margen entero. Fascículos de hojas similares en braquiblastos. Flores pequeñas, blanquecinas-amarillentas, dispuestas en inflorescencias de 0,3-1,5 cm de longitud. Flores masculinas con 10 estambres fértiles; femeninas menores, con 10 estaminodios. Drupa globosa violáceo oscura, de 4 mm diám., con epicarpio papiráceo. Florece en primavera y fructifica en verano.','Borde de bosque ribereño, xerófilo y tierras altas.','Endémica','Ornamental. Melífera. Medicinal (usado en medicina popular como expectorante y purgante, antirreumático, su resina se utiliza para ablandar las callosidades de los pies).'),
  (89,'Schinus molle','L. var. molle','Schinus','molle','aguaribay','gualeguay','falso pimentero','anacahuita','','Árbol','No','Alterna','Compuesta','Imparipinnada','Dentado','Blanco a verdoso','Carnoso','Anacardiaceae','Árbol de 2 a 10 m de altura, frondoso. Tronco robusto, muy ramificado, con ramas más o menos péndulas. Hojas compuestas, alternas, péndulas, imparipinnadas con raquis no alado; pecíolo de 2,5-45,5 cm de long. Flores pequeñas, verdosa-amarillentas en panojas axilares y terminales. Fruto drupa globosa rojiza-violácea, con una sola semilla. Florece en primavera y fructifica en verano.','Bosques ribereños, borde de ruta y caminos vecinales.','Nativa','Ornamental. Melífera. Medicinal (Analgésico, Antifúngico, Antiviral, Cicatrizante, Anticaries). Planta con resina aromática y fruto picante, utilizado como sucedáneo y adulterante de la pimienta. Insecticida.'),
  (90,'Scutia buxifolia','Reissek','Scutia','coronillo','coronilla','','','','','Árbol','Si','Opuesta','Simple','Elíptica','Entero','Blanco a verdoso','Carnoso','Rhamnaceae','Arbolito o arbusto de hasta 10 m de altura. Copa esferoidal. Ramas con hojas opuestas y decusadas, con espinas en las axilas y otras con hojas alternas e inermes. Hojas simples, lustrosas, elípticas, de ápice redondeado, peciolo de 1mm de long. Flores pequeñas, verde-amarillentas, dispuestas en cimas 3-6 floras. Fruto drupa violácea, con 3-4 semillas. Florece en primavera y fructifica en verano.','Bosques xerófilos y ribereños, blanquizales.','Nativa','Ornamental. El follaje es consumido por orugas de la mariposa bandera argentina. Madera utilizada para fabricar postes y como leña. Medicinal (corteza utilizada como tónico cardiaco y diurético). Melífera, pero la planta le otorga aroma desagradable a la miel.'),
  (91,'Sebastiana brasiliensis','Spreng.','Sebastiana','lecherón','blanquillo','palo de leche','','','','Árbol','No','Alterna','Simple','Ovalada','Dentado','Amarillo a anaranjado','Seco','Euphorbiaceae','Árbol de 8 - 10 m. de altura. Corteza gris-verdosa a blanquecina, con látex. Hojas simples, alternas, laticíferas, cortamente pecioladas, ovadas a elípticas, finamente aserradas, glabras, de 3 - 8 cm. de long. x 1,5 - 3 cm. de lat. Flores amarillentas o verdosas, diminutas, dispuestas en espigas terminales u opuestas a las hojas. Fruto cápsula globosa, lisa, castaño clara a rojiza al madurar, constituida por tres cocos unidos entre sí. Semillas 3, carunculadas y de color pardo. Florece en primavera y verano, fructifica en verano.','En bosque ribereños, matorrales, palmares, bosque semixerofilos.','Nativa','Ornamental. Medicinal (se le asignan propiedades para calmar el dolor de muelas y dientes). Combustible, madera utilizada para hacer carbón. Melífera. Utilizada en carpintería y construcciones rurales (en tornería para mangos de herramientas).'),
  (92,'Sebastiana commersoniana','(Baill.) L. B. Sm. & Downs','Sebastiana','palo de leche','blanquillo','','','','','Árbol','Si','Alterna','Simple','Elíptica','Entero','Amarillo a anaranjado','Seco','Euphorbiaceae','Árbol de 4 - 10 m. de altura. Hojas simples, alternas, elíptico-lanceoladas, enteras o apenas dentadas, de 1,5 - 6 cm. de long. x 1 - 2,5 cm de lat. Flores imperfectas, pequeñas, dispuestas en espigas amarillentas en los extremos de las axilas de los tallos. Flores femeninas en la base de la inflorescencia y las masculinas en la parte superior. Fruto cápsula esférica, con tres lóbulos, castaños a la madurez. Semillas ovoides. Florece y fructifica en primavera y verano.','Crece a orillas de ríos y arroyos, en bosque en galería y palmares.','Nativa','Ornamental. Medicinal (externamente se utiliza como antiséptico, el látex se usa para eliminar verrugas). Melífera.'),
  (93,'Sebastiana schottiana','(Müll. Arg.) Müll. Arg.','Sebastiana','sarandí negro','sarandi blanco','sarandi colorado','espina de arroyo','','','Arbusto','Si','Alterna','Simple','Elíptica','Entero','Amarillo a anaranjado','Seco','Euphorbiaceae','Arbusto, de 2 - 4 m. de altura, glabro, con látex incoloro. Hojas simples, alternas, brevemente pecioladas, elíptico-lanceoladas, de 1 - 5 cm. de long. x 0,5 - 1 cm. de lat. Flores unisexuales, apétalas, en racimos axilares espiciformes. Fruto cápsula deprimido-globosa, frecuentemente con apéndices corniculados. Semillas carunculadas. Florece en primavera-verano y fructifica en verano-otoño.','En ribera de río, barrancas y matorrales ribereños.','Nativa','Medicinal (Tallos y hojas poseen actividad antifúngica).'),
  (94,'Senna corymbosa','(Lam.) H.S. Irwin & Barneby','Senna','rama negra','sen del campo','caña fistula','','','','Árbol','No','Alterna','Compuesta','Paripinnada','Entero','Amarillo a anaranjado','Seco','Fabaceae','Arbusto glabro, de 1 a 4 m de altura, con ramas apoyantes, cilíndricas y de color rojo-negruzco con la edad. Hojas compuestas, parapinnadas, con 2-3 pares de foliolos agudos-subagudos, mucronados, con glándula gruesa a la altura de la inserción del primer par de foliolos. Flores amarillas, vistosas, de 2 cm de diám dispuestas en racimos generalmente terminales. Fruto legumbre cilíndrica, tabicada, sin suturas, de color pajizo y de 4,5 a 12 cm de long. Semillas comprimidas, oliváceas. Florece en el verano y fructifica en otoño.','Borde de bosque ribereño, bañados y campos bajos abiertos.','Nativa','Ornamental. Medicinal (hojas usadas en cataplasmas como emoliente y en decocción como drástica, semillas en decocción se utilizan como laxante).'),
  (95,'Sesbania punicea','(Cav.) Benth.','Sesbania','acacia mansa','ceibillo','acacia de bañado','acacia roja','','','Árbol','No','Alterna','Compuesta','Paripinnada','Entero','Rojo a rosado','Seco','Fabaceae','Arbusto de 1 - 4 m. de altura. Hojas compuestas, paripinnadas, alternas, con 8 - 17 pares de folíolos, elípticos, enteros. Flores rojas dispuestas en racimos axilares péndulos, simples. Fruto legumbre con 4 alas longitudinales dehiscentes, bivalva. Semillas ovoides, reniformes, grisáceas, con el tiempo oscuras. Florece en primavera y fructifica en verano.','Crece en las márgenes del río Uruguay y sus afluentes.','Endémica','Ornamental. Las flores se utilizan para fabricar licores y para aromatizar buñuelos. Medicinal (corteza utilizada como astringente en el lavado de heridas). Semillas tóxicas para aves.'),
  (96,'Sesbania virgata','(Cav.) Pers.','Sesbania','rama negra','acacia de bañado','acacia mansa','','','','Arbusto','No','Alterna','Compuesta','Paripinnada','Entero','Amarillo a anaranjado','Seco','Fabaceae','Arbusto de 0,5-4 m de altura, inerme, subglabro. Corteza castaño oscura. Hojas compuestas, alternas, paripinnadas con 7-23 pares de folíolos elíptico-ovales. Flores amarillas menores de 1 cm., dispuestas en racimos axilares péndulos. Fruto legumbre tetrágona, no alada, indehiscente, corchosa, de dispersión hidrófila. Semillas reniformes de color castaño. Florece en primavera-verano y fructifica en otoño.','Común en bañados, islas y campos anegadizos.','Nativa','Ornamental. Las ramas son utilizadas en la fabricación de canastos y artesanías. Melífera. Especie fijadoras de Nitrógeno con potencial para uso en la reforestación de áreas degradadas.'),
  (97,'Solanum glaucophyllum','Desf.','Solanum','varilla','duraznillo blanco','duraznillo de bañado','','','','Arbusto','No','Alterna','Simple','Elíptica','Entero','Azúl a púrpura','Carnoso','Solanaceae','Arbusto, glauco de 1-2 m de altura, rizomatoso con tallo leñoso y raíces gemíferas. Hojas simples, lanceoladas, cortamente pecioladas, enteras, glabras, glaucas en ambas caras. Flores bisexuales azules, dispuestas en cimas seudoterminales plurifloras. Fruto baya carnosa, negro-azuladas de 1 cm de diám. Semillas planas. Florece en verano y fructifica en verano-otoño.','Islas, bordes de lagunas, bañados, zonas bajas','Nativa','Medicinal (los tallos y las hojas se usan para lavajes de heridas, las hojas sin la epidermis maduran granos y en cataplasmas contra reumatismo y hemorroides, los frutos son antioftálmicos, purgante). Tóxica (produce una enfermedad crónica “calcinosis enzoótica” en bovinos, conocida frecuentemente como “enteque seco”). Ornamental.'),
  (98,'Solanum granulosum','Dunal','Solanum','fumo bravo','cambará','tabaquillo del monte','','','','Árbol','No','Alterna','Simple','Elíptica','Entero','Azúl a púrpura','Carnoso','Solanaceae','Árbol de 4 - 6 m. de altura, densamente tomentoso, con pelos estrellados amarillentos. Hojas simples, grisáceas, grandes, afelpadas, pecioladas, alternas, elíptico-lanceoladas, enteras, de 12 - 25 cm. de long. x 5 - 11 cm. de lat. Flores violetas dispuestas en cimas corimbiformes densas, seudoterminales. Fruto baya globosa anaranjada, cubierta de pelos. Semillas chatas y reniformes. Florece en primavera-verano, fructifica en verano.','Margen de los bosques de ribera y en matorrales.','Nativa','Ornamental. Medicinal. (Raíz febrífuga, frutos calmantes, hojas febrífugas, calientes sobre la frente calman el dolor de cabeza; en cataplasmas curan úlceras y alivian catarros). Madera utilizada en artesanías.'),
  (99,'Syagrus romanzoffiana','(Cham.) Glassman','Syagrus','pindó','dátil','chiriba','','','','Palmera','No','Alterna','Compuesta','Paripinnada','Entero','Amarillo a anaranjado','Carnoso','Arecaceae','Palmera arbórea, monoica, de unos 10 - 25 m. de altura. Hojas compuestas, gráciles, curvadas, pinnadas, provistas de segmentos lineales, de 2 - 5 m. de long. Flores lila-crema, protegidas por una espata leñosa. Fruto drupa elipsoide con pericarpio anaranjado. Semilla 1. Florece y fructifica en primavera y verano.','Bosques en galería del río Uruguay y sus afluentes','Nativa','Ornamental. Comestible (Fruto). Medicinal (Raíces utilizadas como anticonceptivo y para la migraña). Hojas usadas en cestería y artesanías. Melífera.'),
  (100,'Terminalia australis','Cambess.','Terminalia','palo amarillo','amarillo de río','','','','','Árbol','No','Alterna','Simple','Elíptica','Entero','Blanco a verdoso','Seco','Combretaceae','Árbol con corteza de color amarillo, de 4 - 10 m. de altura. Hojas simples, alternas, cortamente pecioladas, elípticas u oblanceoladas, glabras, enteras, de nervaduras amarillas, de 8 cm. de long. x 1,5 - 2,5 cm. de lat. Flores blanco-crema a amarillas, apétalas, dispuestas en inflorescencias capituliformes. Frutos sésiles, péndulos, secos, leñosos, elipsoidales, solitarios o agrupados, con ala marginal estrecha. Semilla única, de tegumento delgado. Florece en primavera y fructifica en verano-otoño.','Se distribuye a lo largo de bosques en galería y matorrales ribereños.','Endémica','Ornamental. Medicinal (Corteza: astringente, las hojas poseen actividad antibiótica). Forestal. La corteza presenta taninos. Se emplea la madera localmente para cabos de herramientas. Se utiliza en cestería, tejido de esterillas, etc. Madera para carbón.'),
  (101,'Tessaria integrifolia','Ruiz. & Pav. var. integrifolia','Tessaria','aliso de río','pájaro bobo','','','','','Árbol','No','Alterna','Simple','Lineal','Entero','Rojo a rosado','Seco','Asteraceae','Árbol de 3-8 m de altura, con raíces gemíferas y corteza grisácea. Hojas simples, lanceoladas, agudas, densamente canescentes, de 6-8 cm. de long. Flores rosa-liliáceas dispuestas en capítulos. Fruto aquenio grueso con papús blanco. Florece de verano a otoño y fructifica en otoño-invierno.','En orillas y bancos arenosos del río, generalmente forma bosquecillos compactos.','Nativa','La madera se utiliza para la elaboración de papel y construcciones rústicas. Las cenizas sirven para preparar jabón. Medicinal (se emplea como antigonorreico, cicatrizante y resolutivo). Melífera.'),
  (102,'Tritix praestans','(Vell.) Cabrera','Tritix','tabaquillo','tabaco del monte','','','','','Arbusto','No','Alterna','Simple','Ovalada','Entero','Amarillo a anaranjado','Seco','Asteraceae','Arbusto, con tallos hojosos, de 1,5 - 2,5 m. de altura. Hojas simples, pecioladas, ovado-elípticas, alternas, enteras o aserradas, pubescentes, de 10 - 20 cm. de long. x 3 - 7 cm. de lat. Flores amarillas o anaranjadas, en capítulos, dispuestos en cimas corimbiformes. Fruto aquenio cilíndrico. Papús blanco o amarillento. Florece en invierno y fructifica en verano.','Crece en matorrales, barrancas y en el interior de bosques en galería y semixerófilos.','Nativa','Ornamental, flores muy perfumadas. Melífera.'),
  (103,'Vernonanthura montevidensis','(Spreng.) H. Rob.','Vernonanthura','chilca','','','','','','Arbusto','No','Alterna','Simple','Elíptica','Entero','Rojo a rosado','Seco','Asteraceae','Arbusto, de 0,80 - 3 m. de altura. Hojas simples, alternas, coriáceas, oblanceoladas, enteras o levemente dentadas, de 15 - 40 mm. de long. x 3 - 6 mm. de lat. Flores rosadas en capítulos muy numerosos dispuestas en cimas corimbiformes en los extremos de las ramas. Fruto aquenio sedoso-pubescente. Papús blanco o amarillento. Florece en primavera y verano, fructifica en verano.','Frecuente en suelos arenosos, en pajonales, palmares y borde de bosques ribereños.','Nativa','Ornamental. Melífera.'),
  (104,'Xylosma venosa','N.E. Br.','Xylosma','espina colorada','','','','','','Árbol','Si','Alterna','Simple','Ovalada','Dentado','Amarillo a anaranjado','Carnoso','Salicaceae','Árbol de 2 - 6 m. de altura, corteza pardo-grisácea, inerme o con espinas axilares de 1 a 5 cm. Hojas simples, alternas, ovado-lanceoladas, orbiculares o casi rómbicas, irregularmente crenado-aserradas, provistas de dos glándulas en contacto con la base de las hojas, de 4,5 - 9,3 cm. de long. x 2 - 5,1 cm. de lat. Flores amarillo-verdosas, dioicas, pequeñas, fragantes, dispuestas en grupos axilares. Fruto baya ovoide-globosa, rojo volviéndose negruzco al secarse, brillante. Semillas ovoides, comprimidas, brillantes. Florece y fructifica en verano.','En borde de bosques y costas ribereñas, lugares abiertos, matorrales y pastizales, borde de caminos.','Nativa','Melífera. Medicinal (Hojas y ramas en decocción se usan para lavado de llagas). Melífera.'),
  (105,'Zanthoxylum rhoifolium','Lam.','Zanthoxylum','tambetarí','teta de perra','cuentrillo','','','','Árbol','Si','Alterna','Compuesta','Imparipinnada','Crenado','Blanco a verdoso','Carnoso','Rutaceae','Árbol de hasta 12 metros de altura, tronco con mamelones cónicos, espinosos y ramas jóvenes con aguijones rectos y con pelos fasciculados y simples. Hojas compuestas, imparipinnadas con 3 a 8 pares de foliolos asimétricos y sésiles. Flores pequeñas, pentámeras y amarillentas, en inflorescencias terminales. Fruto rojizo, de mericarpos uniseminados de 5 mm de diam. Semillas negras brillantes. Florece en verano y fructifica en verano-otoño.','Borde de bosque ribereño.','Nativa','Ornamental. Medicinal (Utilizada contra la malaria. La Corteza se usa como antinflamatoria, para calmar el dolor de muelas y oídos). Melífera.');`;

}
